### ISSUE TITLE
Chat doesn't show proper names

### ISSUE THREAD

**Issue by mjkzy** [momo5502/boiii#107]
pretty sure this is to do with the steam emulation if I had to guess. lobby chat doesn't work too, but that's the least of worries atm

![image](https://user-images.githubusercontent.com/64374267/211422877-132f3114-b5f5-4c74-b179-47d5845a5f94.png)
![image](https://user-images.githubusercontent.com/64374267/211422883-d2157ac0-c691-4102-b7cb-f803c2be1d15.png)

**Comment by diamante0018** [comment]
fixed on develop
