### ISSUE TITLE
Microphone Audio being lowered on startup.

### ISSUE THREAD

**Issue by Flam3z** [momo5502/boiii#108]
Don't know if you have experienced this personally but me and many other people have an issue to where bo3 lowers microphone audio for whatever reason and was just curious if this will be addressed.

**Comment by Dss0** [comment]
Can you check if this is fixed after turning off exclusive mode for your mic? The setting is called "allow applications to take exclusive control of this device" in the sound device properties.

**Comment by Flam3z** [comment]
I never had this setting on.

**Comment by Resxt** [comment]
Just for reference this is an issue with the game itself.
Happens to a lot of people on Steam too
The way I fixed it was by setting the game's mic volume to 0 or to the same volume I have set in Windows
