### ISSUE TITLE
how do you build the solution?

### ISSUE THREAD

**Issue by ghost** [momo5502/boiii#110]
can you post instructions on how to build the solution, i tried building it on vs 2019 and it threw up a load of errors.

**Comment by Crugnok** [comment]
got it built but all it is is a dll tlsdll.dll, sorry new to this stuff. is it supposed to be just a dll file?

**Comment by momo5502** [comment]
You need vs2022

**Comment by Crugnok** [comment]
oh donno why i wrote 2019, i have 2022 installed.

is it supposed to build more than just a dll file or is that it? 

i still got two errors on building the solution

Severity	Code	Description	Project	File	Line	Suppression State
Error		C:/Users//Documents/GitHub/boiii/premake5.lua:156: bad argument #1 to 'match' (string expected, got nil)	client	C:\Users\\Documents\GitHub\boiii\build\EXEC	1	
Error	MSB3073	The command "pushd ..
tools\premake5 generate-buildinfo
popd
:VCEnd" exited with code 1.	client	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets	149

**Comment by momo5502** [comment]
you need to clone the git repo. downloading as zip will not work

**Comment by Crugnok** [comment]
yeah i realised that on the first attempt. i then cloned it with the git desktop app. still not sure what i'm supposed to end up with as the there's no readme or instructions. thought it might help me getting the game to work with a d3d11 wrapper (3dmigoto)
as it crashes the game. i read that bo3 doesn't like 3rd party dlls. saw the list of things your project does but no idea how to use it or if it would help?

**Comment by momo5502** [comment]
you will get a boiii.exe that you can drop in your game folder and run, however things are still unstable, so there is no support given for anxthing and things are as is, hence no instructions on how to do anything

**Comment by Crugnok** [comment]
got it to build, i hadn't installed all the required dependencies.

**Comment by slimyshine** [comment]
> got it to build, i hadn't installed all the required dependencies.

@Crugnok Could you teach me how to build it or send me your build? Add me on discord slimyshine#7039

**Comment by Manolo5678** [comment]
Hi @Crugnok can you help me a little bit? I need help installing the dependencies.

**Comment by Crugnok** [comment]
> > got it to build, i hadn't installed all the required dependencies.
> 
> @Crugnok Could you teach me how to build it or send me your build? Add me on discord slimyshine#7039

download the latest visual studio community edition which is free

i think i installed

desktop development with c++ 
universal windows platform development
python development

you don't have to install every component though under all three.

vs tells you what's missing but sometimes it's vague. i just kept installing stuff till it compiled.

**Comment by Manolo5678** [comment]
Idk why, but I keep getting this error:

Error MSB3073 The command "pushd ..
tools\premake5 generate-buildinfo
popd
:VCEnd" exited with code -1073741502. client C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets 149

**Comment by momo5502** [comment]
The client is in an early state and is not meant to be used yet. The fact the you are struggling with the compilation shows you are not supposed to use it yet. As soon as it is usable, instructions will be posted.
