### ISSUE TITLE
3dmigoto crashes / hangs the game on black screen

### ISSUE THREAD

**Issue by ghost** [momo5502/boiii#112]
hi, 
could you test 3dmigoto and see if you can get it working? i've been using it on other cod games to remove things like depth of field and other annoying effects. refuses to work on black ops 3 though, think it's because it has checks for 3rd party dlls ?

i've tried various dll injectors and all fail, even processhacker.

project is at https://github.com/bo3b/3Dmigoto & https://github.com/bo3b/3Dmigoto/releases

it's a d3d11 wrapper for shader hunting.

on both vanilla game and boiii it crashes after campaign cutscene (when i click mouse to skip) hangs on a black screen and then makes a dump file.

for some reason it only crashes after cutscenes for campaign and zombies (haven't tried it in offline mp) doesn't crash game on menus or in the campaign hq.

**Comment by momo5502** [comment]
If it crashes in vanialla as well, this has nothing to do with this project.
