### ISSUE TITLE
3dmigoto crashes / hangs the game on black screen

### ISSUE THREAD

**Issue by ghost** [momo5502/boiii#113]
please don't close the issue again, i beg to differ about it not applying to your project, it's a useful tool for all d3d11 games.

you obviously haven't disabled all the restrictions, like your list of features states, i'd appreciate if you could investigate the issue.

and if others report it, what then? the whole point users reporting issues with gits is to investigate what causes said issues. as things can conflict.

-------------
hi,
could you test 3dmigoto and see if you can get it working? i've been using it on other cod games to remove things like depth of field and other annoying effects. refuses to work on black ops 3 though, think it's because it has checks for 3rd party dlls ?

i've tried various dll injectors and all fail, even processhacker.

project is at https://github.com/bo3b/3Dmigoto & https://github.com/bo3b/3Dmigoto/releases

it's a d3d11 wrapper for shader hunting.

on both vanilla game and boiii it crashes after campaign cutscene (when i click mouse to skip) hangs on a black screen and then makes a dump file.

for some reason it only crashes after cutscenes for campaign and zombies (haven't tried it in offline mp) doesn't crash game on menus or in the campaign hq.

**Comment by momo5502** [comment]
the whole point of reporting issues is that you can solve problems related to the project you are reporting the issue to. this is not an issue related to this project. if it makes a dump file, that means there is a bug in the project you are using. this has nothing to do with any restrictions. a dump means a crash, a crash means a bug. therefore this is clearly a bug in a seperate project other than this one. feel free to create an issue there, but please refrain from opening issues that are not related to this project.

**Comment by Crugnok** [comment]
apologies then, i'm still new to all this git stuff. i will contact the creators on the wrapper instead.
