### ISSUE TITLE
Varieties Of Spawnbot Character

### ISSUE THREAD

**Issue by amrurikaj** [momo5502/boiii#119]
Hi sir,

if this can be done, maybe you can make varieties of spawnbot character. I tested previously looks like the character spawn for the bots is only Ruin model. It makes me harder to know whether it is enemy or my friends. If this cannot be done, you are please to close this ticket. Thanks
![image](https://user-images.githubusercontent.com/113702897/215229807-a4d109c5-e404-4a28-9af2-3d8751a3d33c.png)

**Comment by momo5502** [comment]
This is a good issue for contributors. I think it should easily be doable. As this has low priority, I won't do it right now, but others who would like to contribute can try to fix this.

**Comment by muzakkir280595** [comment]
this one I agree need to be fixed I mean not important but for people who like to play in bot server this is better to have :-D

**Comment by diamante0018** [comment]
I don't think this should be fixed by the client.
Spawnbot is an hack command so to speak.
The way the original Devs add bots is by setting a dvar with a number of bots they want to spawn from the console then a game script takes care of the rest
https://github.com/DoktorSAS/GSC/blob/main/IW6/autobots.gsc

This is how the variety (non-issue imo) was fixed on iw6x
The original gsc function for the bots must be used

**Comment by VERsingthegamez** [comment]
> Spawnbot is a rudimental function that should really just be used for adding test clients to the game. For gameplay bots should be adding using the games population monitoring functions. To use this in public matches or custom games simply select how many bots you want in the bot settings menu, and for servers add the following to the config:
> 
> ```
> set bot_maxallies "6"    // Amount of Bots on the Friendly Team
> set bot_maxAxis "6"     // Amount of Bots on the Enemy Team
> set bot_maxFree "8"    // Number of bots for non-teambased game modes
> set bot_difficulty "1"    // Bot Skill. (0 - Easy, 1 - Normal, 2 - Hard, 3 - Veteran)
> ```

In Public lobbies, setting the bots through the Setup Game Option, does not add bots in the game no matter what the number is on each side. Only Spawnbot spawns them in.
