### ISSUE TITLE
How can I join a lobby?

### ISSUE THREAD

**Issue by rnblanco** [momo5502/boiii#120]
Can somebody explain to me how the P2P works?
I am trying to join a lobby and I am unable to do it.
I am using ZeroTier for P2P connection and I think that is kind of weird that shows 127.0.0.1 as the external IP and ZeroTier IP as the internal IP, I am a bit confused if it is a bug or if that is the way it is supposed to work.

**Comment by LevelChecker** [comment]
Theres no matchmaking if thats what youre talking about and dedicated servers are currently being worked on

**Comment by LevelChecker** [comment]
If you start a lobby you can connect p2p using the console "connect ipaddress"

**Comment by LevelChecker** [comment]
Im not familiar with ZeroTier myself so im unsure how that will work

**Comment by momo5502** [comment]
no matchmaking support
