### ISSUE TITLE
Error when alt tabbing out of the client.

### ISSUE THREAD

**Issue by SwordSWD** [momo5502/boiii#125]
![image](https://user-images.githubusercontent.com/62721069/215703558-7df33bac-7eaa-4a24-82d1-2033188107dc.png)

**Comment by SwordSWD** [comment]
[boiii.exe.CODBUILD15-764.CL#3421987.1675152431.zip](https://github.com/momo5502/boiii/files/10544241/boiii.exe.CODBUILD15-764.CL.3421987.1675152431.zip)
Here is a dumpfile also.

**Comment by momo5502** [comment]
It's either related to your graphics card or the responsible drivers. There is nothing i can do here.
