### ISSUE TITLE
Adding a server to favourites does not show in favourites

### ISSUE THREAD

**Issue by vos6434** [momo5502/boiii#134]
Game says server is added to favourites but the server does not show up in favourites.
![image](https://user-images.githubusercontent.com/21976486/218116121-476cec3f-0f60-4dbc-83ab-c2c36d5a7e28.png)
![image](https://user-images.githubusercontent.com/21976486/218116189-0a882c20-624e-4b80-8068-88a8b26f8088.png)

**Comment by momo5502** [comment]
That's a feature, i haven't implemented favourite emulation

**Comment by diamante0018** [comment]
Completed
