### ISSUE TITLE
Unable to change teams on a server

### ISSUE THREAD

**Issue by vos6434** [momo5502/boiii#135]
![image](https://user-images.githubusercontent.com/21976486/218122996-f04315a5-35ca-42ac-95c0-28501ab21cdc.png)
When in a team, you can only choose spectator, while a spectator you can only choose auto assign which always places you on the same team resulting in team players vs ai.
![image](https://user-images.githubusercontent.com/21976486/218123205-4d81a4a5-9b45-4004-94fd-90e485c1b749.png)

**Comment by diamante0018** [comment]
Was fixed by adding a modified GSC file to boiii 's client files
