### ISSUE TITLE
Private matches/Solo games break after joining a dedicated server

### ISSUE THREAD

**Issue by Brentdevent** [momo5502/boiii#137]
After joining a dedicated server, it seems to break anything related to solo games. Zombies, campaign and custom games stop working.
Rebooting the game fixes the issue.

Following screenshots contains the error messages that pop ups after failing to load the map:

**Zombies solo game:**
![bug-solo-after-dedi-joined](https://user-images.githubusercontent.com/70229620/218140326-3506ae8c-bd16-4f07-a6d4-3009a598ebe4.png)

**Custom game:**
![bug-custom-after-dedi-joined](https://user-images.githubusercontent.com/70229620/218140363-85d3989a-6ff4-40f9-add1-3774ac7ac22e.png)

**Comment by momo5502** [comment]
I know why this happens. That's because I'm a lazy fucker xD
