### ISSUE TITLE
minicrash dump

### ISSUE THREAD

**Issue by RyhZM** [momo5502/boiii#138]
[boiii-crash-2023-02-10-23-10-30.zip](https://github.com/momo5502/boiii/files/10711854/boiii-crash-2023-02-10-23-10-30.zip)

**Comment by vos6434** [comment]
How and when did the crash happen? A little more context would be very useful.

**Comment by RyhZM** [comment]
> How and when did the crash happen? A little more context would be very useful.

happened soon before i had reported it here. context is i was just loading up the game. done nothing to files. crashed. tried again and worked fine and never crashed again

**Comment by momo5502** [comment]
Closing this, as it's for the old binary.
