### ISSUE TITLE
BOIII  Crash Dump

### ISSUE THREAD

**Issue by monocolotion** [momo5502/boiii#139]
BOIII Crash Dump

Version: v0.0.1-312-ga2707ab
Timestamp: 2023-02-10-18-10-40
Exception: 0xC0000005
Address: 0x7FF6037B5FBC
Base: 0x7FF6016E0000
[boiii-crash-2023-02-10-18-10-39.zip](https://github.com/momo5502/boiii/files/10713654/boiii-crash-2023-02-10-18-10-39.zip)

OS Version: 6.2

**Comment by momo5502** [comment]
Pretty sure it's fixed by this: 7a6d5b71122cc9fcd510b772f1500ce93e4831cb
If not, please reopen

**Comment by momo5502** [comment]
This one's definitely fixed. Address matches :3

**Comment by monocolotion** [comment]
thank
