### ISSUE TITLE
The launcher won't connect to my own server without an internet connection

### ISSUE THREAD

**Issue by Matiasm500** [momo5502/boiii#140]
When I create the server with no connection in my PC or in my router, i try to launch the game offline and then i type /connect localhost:28961 the game freezes

**Comment by Matiasm500** [comment]
Server in offline:
![image](https://user-images.githubusercontent.com/96822329/218266440-2c1044f0-44cc-4f94-82de-d0947c80c39b.png)

**Comment by Matiasm500** [comment]
Client before enter the command:
![image](https://user-images.githubusercontent.com/96822329/218266471-41348a5e-169c-423f-ac18-50f82cc93ef2.png)

**Comment by Matiasm500** [comment]
After send the command: (Its freezed the screen)

![image](https://user-images.githubusercontent.com/96822329/218266537-7425fb5a-36d3-406c-981d-354a902d19b8.png)

**Comment by momo5502** [comment]
Try not using localhost but some internal ip instead. CODs used to have issues with localhost connections

**Comment by Matiasm500** [comment]
I tried with my pc ip without the router (127.0.0.1:29861), with other router (192.168.1.100:28961) and with my local router ip (192.168.0.200:28961) but the game still freezeing

**Comment by Matiasm500** [comment]
Now I tried to do it with internet and the game freezes

**Comment by momo5502** [comment]
Pretty sure it's fixed by this: 7a6d5b71122cc9fcd510b772f1500ce93e4831cb
If not, please reopen

**Comment by Matiasm500** [comment]
Yes, It's solved
