### ISSUE TITLE
Load Custom GSC Scripts

### ISSUE THREAD

**Issue by pistakilla** [momo5502/boiii#142]
As the title suggests, adding compiled GSC scripts would be appreciated. Also, add this feature to dedicated servers to ensure mods are in a server without needing to load a mod that the client is required to download.

**Comment by diamante0018** [comment]
The client supports this, I think the issue can be closed or changed to support loading 'raw' GSC files.
Although loading already compiled GSC files should be more than fine for now.

**Comment by diamante0018** [comment]
This feature was indeed added and you can load compiled GSC scripts.
Xensik will work on an embeddable GSC compiler in the meantime but I don't think it's a priority right now.

**Comment by momo5502** [comment]
The client doesn't support this, or am i wrong?
You can override gscs from the basegame, but not add custom ones

**Comment by diamante0018** [comment]
I must have understood the issue wrong then, Oops.
