### ISSUE TITLE
Game console takes the executable's shortcut as the game path

### ISSUE THREAD

**Issue by OscarDL** [momo5502/boiii#144]
Just noticed after creating a shortcut for boiii.exe, in the folder where I start all my other games from, that the game tries to start from the shortcut's path instead of the actual game destination path, and therefore won't start at all because it can't find any of the assets.

![image](https://user-images.githubusercontent.com/27915933/218279128-9963b639-7a7b-4534-8da8-66ddd4ce9af8.png)
![image](https://user-images.githubusercontent.com/27915933/218279130-19972aeb-5cb2-40d5-a4c1-80d3db77c1e3.png)

**Comment by momo5502** [comment]
Are you sure that's not an issue with the shortcut? Have you checked that the working directory points to the game?

**Comment by OscarDL** [comment]
> Are you sure that's not an issue with the shortcut? Have you checked that the working directory points to the game?

Sorry for the (sort of) late reply, you're totally right, my shortcut was completely broken for some odd reason. Never happened to me before so I assumed it was the client's fault. Created a new one and it works fine now, thanks!
