### ISSUE TITLE
Stuttering on AMD CPUs

### ISSUE THREAD

**Issue by HackersinSpace** [momo5502/boiii#147]
Currently this affects people with AMD CPUs. The game has trouble keeping a smooth constant framerate because of multithreading on AMD CPUs. The only known fix is to open task manager, go to details on the left (Windows 11), right click BO3, click Set Affinity, make sure only 4 cpu cores are checked then press ok then click Set Affinity again and re-enable all cores. Such a bizarre bug and hoping this will get resolved using BOIII.exe.

**Comment by Dss0** [comment]
I have a ryzen 2700x and don't have any issues with stuttering.

**Comment by momo5502** [comment]
I'll mark this as fixed. It can be reopend if that's not the case
