### ISSUE TITLE
Unlock Some DVAR Commands

### ISSUE THREAD

**Issue by HackersinSpace** [momo5502/boiii#148]
I noticed that the console is enabled on BOIII.exe. However the commands /r_dof_enable (enables/disables Depth Of Field) and /r_lodbiasrigid (increases draw distance/level of detail) are disabled so I can't use it. It would be beneficial to have these DVARs unlocked so people can improve the graphical fidelity of the game at their own leisure without having to resort to a mod.

**Comment by rhobiusvoid** [comment]
Gonna add this here for a visual demonstration of DoF.
![image](https://user-images.githubusercontent.com/22803374/222177673-625d14af-600b-4483-82f9-4a2cb40ec594.png)
