### ISSUE TITLE
Unable to join password protected servers

### ISSUE THREAD

**Issue by SadSlothXL** [momo5502/boiii#152]
When trying to join a password protected servers there is no prompt to enter a password resulting in the client trying to connect and getting rejected for invalid password.

![image](https://user-images.githubusercontent.com/105758694/218328733-ddc84e5a-9b30-47c7-b621-fa7c77fb70d0.png)

**Comment by SwordSWD** [comment]
![image](https://user-images.githubusercontent.com/62721069/218330429-02ea3f9c-69fd-47b5-9920-59c095adbf3a.png)
It's also saying that the password dvar doesn't exist.

**Comment by 4doorsmorehoes** [comment]
On normal bo3. Joining a server a pop menu exist
![image](https://user-images.githubusercontent.com/38188579/225406232-bc615a7b-5867-4f10-8ab3-a51f64e98a2c.png)

**Comment by diamante0018** [comment]
I have a pr going that will register the password command client side. it will require another patch to make it actually work tho
