### ISSUE TITLE
Game freezes when you leave a server browser match if you join from a different game mode e.g. Zombies

### ISSUE THREAD

**Issue by ethanjones99** [momo5502/boiii#157]
So I noticed that I would get stuck on a checkerboard screen if I left an mp server browser game if I opened the server browser from a different game mode. I tried zombies and campaign, and they both freeze, which requires me to alt f4. The console can still be opened on the screen, so it doesn't seem frozen entirely.

**Comment by ethanjones99** [comment]
https://imgur.com/a/r5RMgzp

screenshots of the console and game

**Comment by momo5502** [comment]
This is highly likely a duplicate of #149, so I'm gonna close this one for now.
