### ISSUE TITLE
More Functionality for Bots in Public

### ISSUE THREAD

**Issue by VERsingthegamez** [momo5502/boiii#169]
Bots only play as Ruin, their aim is bad no matter what difficulty you put them on, they don't want to spawn streaks as much, they only use base character camo, no attachments on weapons or camos, and weapon variety could use more including the dlc weapons. Perk's I'm not sure if they do but I haven't seen flak jacket on a single one. Also if its possible, add ranks to bots and they go up as you go up with their loadouts changing as well.

**Comment by LevelChecker** [comment]
The ruin only will probably have to be fixed but iirc theres Mods in the workshop for Better Bot support so they arent as dumb which will be able to use on the servers

**Comment by VERsingthegamez** [comment]
> 

Yup. So I'm sure its a somewhat easy fix at some point. It's not entirely high on the priority list currently.

**Comment by momo5502** [comment]
#126
