### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Xepster** [momo5502/boiii#178]
Attached is the minidump.

[boiii-crash-2023-02-16-02-10-46.zip](https://github.com/momo5502/boiii/files/10753193/boiii-crash-2023-02-16-02-10-46.zip)

**Comment by momo5502** [comment]
X:\Games\Call of Duty - FitGirl Releases\Call of Duty - Black Ops 3 - MP\boiii.exe

**Comment by momo5502** [comment]
No support for non-steam versions of the game.

**Comment by momo5502** [comment]
Get clean game files and then retry again
