### ISSUE TITLE
Game freeze on host PC when attempting to connect to it

### ISSUE THREAD

**Issue by ImAciidz** [momo5502/boiii#179]
Process dump (hopefully I did this correctly): https://drive.google.com/file/d/1pboZPnNCNgowZI0dPk6xklDXqLNW0DKj/view?usp=share_link
Video demonstration: https://youtu.be/-s4rn9PToEQ
Doesn't seem to matter if host is in main menu, mp, or zm

**Comment by ImAciidz** [comment]
Commit [3168e70](https://github.com/momo5502/boiii/commit/3168e707905a5d3b9791d36e056c0636ee985f71) is where the crashes start

**Comment by momo5502** [comment]
It's not a crash tho
