### ISSUE TITLE
Zombies Dedicated Servers

### ISSUE THREAD

**Issue by NathanielRobson** [momo5502/boiii#183]
Server browser functionality to join modded and unmodded servers for Zombies. 
Same functionality as Bo2 Plutonium server browser.
Can join games in progress and game doesn't end if all players leave.

**Comment by Dss0** [comment]
For reference i'm posting the info JezuzLizard gave me here so it doesn't get lost:
 The dedicated server can already load zombies maps however it also needs to load zm_common.ff which contains a lot of scripts required by the maps, you can get it to load that by setting the sessionmode to zombies ([This mod by JezuzLizard does this](https://github.com/JezuzLizard/T7-18-Player-Dedicated-Zombies-Server-Mod)). Would probably be more elegant to do this in the client (if gametype is zclassic switch sessionmode to zm). For playlist servers the menus would also have to be modified so zombie maps show in the lobby and so on but this may not be necessary when hosting match (server.cfg) servers.
 Obviously the zombie fastfiles also need to be moved to the dedicated server directory.

**Comment by Brentdevent** [comment]
I've got it working, but it seems issue #137 needs to be fixed first. The server is in the server list but I can't join it due the same error. I haven't found a solution yet.
