### ISSUE TITLE
Combine Classic and Mega Gobblegums into a single category

### ISSUE THREAD

**Issue by vos6434** [momo5502/boiii#184]
Since Mega gobblegums are unlimited, having all gobblegums under 1 category would be a nice enhancement.

**Comment by Lierrmm** [comment]
This can be done by overriding `DataSources.BubbleGumTabType` which is found in `datasources.lua`.

At the moment it creates two tables with two different filters: `bubblegum_consumable` and `bubblegum`. `bubblegum_consumable` being the Mega Gobblegums.

**Comment by momo5502** [comment]
honestly, i'm not sure if this is needed

**Comment by diamante0018** [comment]
Not needed, this falls under the category of game mods. We should not modify the stock gameplay behaviour ourselves. As it was pointing out. It's already possible by modifying the lua files.
