### ISSUE TITLE
Game freezes and closes after last update

### ISSUE THREAD

**Issue by FrancescoCode1** [momo5502/boiii#194]
Tested in Zombies and Multiplayer mode > local games. Game freezes even in the lobby after sitting 2 minutes in idle.
DMP files are all corrupted
![image](https://user-images.githubusercontent.com/71893290/219710574-5bcdff47-f20e-4391-a3a8-f1eb508d3b6f.png)

**Comment by momo5502** [comment]
Can you try again with the latest update?

**Comment by momo5502** [comment]
And delete all dumps in that folder. If it still crashes, try to upload them again

**Comment by FrancescoCode1** [comment]
Tested again, no more crashes since last update
