### ISSUE TITLE
Gobblegums

### ISSUE THREAD

**Issue by sharks90** [momo5502/boiii#199]
what happened to the mega gobblegums they're gone now as well as the standard ones being locked.

**Comment by pistakilla** [comment]
You need to enable "Unlock all loot", but first you need the [lua ](https://download-directory.github.io/?url=https://github.com/momo5502/boiii/tree/main/data)files to see the "stat" button that's it mp > public match > stats.

Also, lvl your character up to unlock the classic ggs.
