### ISSUE TITLE
GobbleGums problem "Out of" 

### ISSUE THREAD

**Issue by Alucard935** [momo5502/boiii#203]
In Lan mode just 1 person can use the mega gums and that person is the host. The other pc just can use the standar gums and the megas appear like sold out

**Comment by ahaider786** [comment]
Yeah tried it same problem.

**Comment by Pussio57** [comment]
bump

**Comment by momo5502** [comment]
it's a client side hook to increase the amount, that's why

**Comment by Alucard935** [comment]
and on the servers zombie 2 it's the same problem 
![image](https://user-images.githubusercontent.com/107876885/221223464-5f16f8cc-ae0b-4a53-bf8e-f03882f0b5a8.png)

**Comment by hallinbirch** [comment]
has anyone mentioned that this problem is on all zombies modes for people like me who can't even get consumable GG to work in solo

**Comment by diamante0018** [comment]
There is a fix in scripts.cpp assuming this is fixed.
