### ISSUE TITLE
GeForce Experience does not recognize boiii

### ISSUE THREAD

**Issue by liveskai** [momo5502/boiii#215]
# GeForce Experience does not recognize boiii

**Comment by momo5502** [comment]
What? Then add it manually?

**Comment by momo5502** [comment]
More descriptive issues would be very helpful

**Comment by liveskai** [comment]
> What? Then add it manually?

Unable to record games

**Comment by momo5502** [comment]
that sounds like an issue nvidia has to deal with

**Comment by liveskai** [comment]
> > What? Then add it manually?
> 
> Unable to record games
Steam version can be used normally

**Comment by 0x526f6d656f** [comment]
You should be able to manually add the .exe to GeForce Experience to have ShadowPlay working.

**Comment by liveskai** [comment]
> You should be able to manually add the .exe to GeForce Experience to have ShadowPlay working.

How to add manually

**Comment by liveskai** [comment]
> You should be able to manually add the .exe to GeForce Experience to have ShadowPlay working.

Only the directory can be selected, not the exe

**Comment by liveskai** [comment]
> More descriptive issues would be very helpful

GeForce Experience only recognizes BlackOps3.exe, not boiii.exe

**Comment by 0x526f6d656f** [comment]
> > More descriptive issues would be very helpful
> 
> 
> 
> GeForce Experience only recognizes BlackOps3.exe, not boiii.exe

I'll give this a try when I'm home.
