### ISSUE TITLE
Add commands Disconnect

### ISSUE THREAD

**Issue by RywaZ** [momo5502/boiii#220]

**Comment by momo5502** [comment]
please provide some description on what this is actually about

**Comment by RywaZ** [comment]
> please provide some description on what this is actually about

do like plutonium add a "disconnect" command for example to disconnect from a server or for example if the game has a bug and we are of an infinite load by joining a server 
![image](https://user-images.githubusercontent.com/124745850/220527328-b26c031d-5c01-49a4-ba43-d20ed701d974.png)

**Comment by momo5502** [comment]
the game already has it and you can even see that in your screenshot. you probably forgot the / at the beginning and thus typed in the chat

**Comment by RywaZ** [comment]
> the game already has it and you can even see that in your screenshot. you probably forgot the / at the beginning and thus typed in the chat

Oh yeah sorry i forgot the / my bad
