### ISSUE TITLE
Console Window TopFront

### ISSUE THREAD

**Issue by hosseinpourziyaie** [momo5502/boiii#24]
bring console window to front at the end of create_console (console.cpp L150)

`SetWindowPos(*game::s_wcd::hWnd, HWND_TOPMOST, 0, 0, 0, 0, SWP_NOMOVE | SWP_NOSIZE | SWP_SHOWWINDOW);
SetWindowPos(*game::s_wcd::hWnd, HWND_NOTOPMOST, 0, 0, 0, 0, SWP_NOMOVE | SWP_NOSIZE | SWP_SHOWWINDOW); // Revert back to allow other possible Messageboxes to show-up`

*All of other alternative ways are not working for some odd reason (BringWindowToTop,SetForegroundWindow,SetActiveWindow,etc)

**Comment by momo5502** [comment]
Feel free to create a PR

**Comment by coconutbird** [comment]
> bring console window to front at the end of create_console (console.cpp L150)
> 
> `SetWindowPos(*game::s_wcd::hWnd, HWND_TOPMOST, 0, 0, 0, 0, SWP_NOMOVE | SWP_NOSIZE | SWP_SHOWWINDOW); SetWindowPos(*game::s_wcd::hWnd, HWND_NOTOPMOST, 0, 0, 0, 0, SWP_NOMOVE | SWP_NOSIZE | SWP_SHOWWINDOW); // Revert back to allow other possible Messageboxes to show-up`
> 
> *All of other alternative ways are not working for some odd reason (BringWindowToTop,SetForegroundWindow,SetActiveWindow,etc)

you can use [SetForegroundWindow](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setforegroundwindow)

**Comment by momo5502** [comment]
> > *All of other alternative ways are not working for some odd reason (BringWindowToTop,SetForegroundWindow,SetActiveWindow,etc)
> 
> you can use [SetForegroundWindow](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setforegroundwindow)

Did you even read the post? He said SetForegroundWindows is not working
