### ISSUE TITLE
Dedicated Servers open two Sockets that can conflict with each other

### ISSUE THREAD

**Issue by Dss0** [momo5502/boiii#251]
### Bug Type

Dedicated Server

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Windows Server 2019

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. Start a dedicated Server
2. Close the dedicated Server
3. Wait x amount of time (i waited up to 10 mins) and Start the dedicated Server again

### Expected Result

Server uses the default Port

### Actual Result

Server uses one Port after the default one, e.g. if default port set is 28960 it will now use 28961 despite no service occupying 28960.

### (Optional) Proof and Additional Information

netstat shows no usage for the server's port yet it binds to the next one, restarting the entire system fixes this.

### Severity/Priority

Medium

**Comment by momo5502** [comment]
All process resources are automatically released when a process terminates. Including all sockets. This issue can not occur unless you somehow misconfigured your PC. I cannot reproduce this either.

**Comment by momo5502** [comment]
29000 is not the default port meaning you are using a custom built binary? are you sure you did not goof it on your end? I can not reproduce anything alike.
![image](https://user-images.githubusercontent.com/4027748/221843093-0195fc1b-3617-4cea-aec5-a3bef8a956e9.png)

**Comment by Dss0** [comment]
yes i built it myself but the only thing i changed is the port in network.cpp, nothing else. I did this because i could not get my server to show up at all when using the default port, wasn't possible to connect to it via lan ip either (maybe because client + server use 28960?).
I wouldn't know which windows-side configuration would cause something like this and it doesn't happen with any of my other services that run on this server (including iw4x and s1x servers).
I will continue testing..

**Comment by Dss0** [comment]
Found the issue, the server actually opens a socket on the port set via net_port AND one on the port hardcoded into the client right now, only that it's only possible to connect to it on the hardcoded port.
I set net_port in my startup parameters to 29001, 02, 03 in preparation for when this will actually work but it seems it already sort of does so that caused some conflicts.

**Comment by momo5502** [comment]
ah i see, good point, we should keep this issue open (maybe rename it?) to address fixing or removing the game socket then. good find

**Comment by momo5502** [comment]
23487b2ff358ba752154145ba87913645a0630a4
