### ISSUE TITLE
Set custom Dedicated Server Port

### ISSUE THREAD

**Issue by Dss0** [momo5502/boiii#252]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

I'm sure everyone is already aware of this but i'm just putting it here so it's not forgotten. Setting net_port to a user defined Port is a necessity for Dedis.

**Comment by Ston3Cold** [comment]
Agreed, would also appreciate this as asking my ISP to forward ports for my VPS is a bit tedious. Would rather just use whatever ports are currently open to host.

**Comment by momo5502** [comment]
23487b2ff358ba752154145ba87913645a0630a4
