### ISSUE TITLE
FFA & GunGame Scoreboard Broken

### ISSUE THREAD

**Issue by 4doorsmorehoes** [momo5502/boiii#255]
### Bug Type

Client, Dedicated Server

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

Set and run server with gametype gun or dm
Join server and press scoreboard tab. It seem to be going by team base 

### Expected Result

Should be non team scoreboard

### Actual Result
See screenshot

### (Optional) Proof and Additional Information

![boiii_2023-02-28_12-16-46](https://user-images.githubusercontent.com/38188579/221930285-81920dcf-8e9d-474e-9925-ce60ea798041.jpg)

### Severity/Priority

Medium

**Comment by Brentdevent** [comment]
Thank you for reporting your findings @WantedDV, I was able to pinpoint the issue easily because of it!
Made a mistake by just setting the gametype but not loading the default config settings.
