### ISSUE TITLE
Project Viking not saving my game.

### ISSUE THREAD

**Issue by HackersinSpace** [momo5502/boiii#264]
This has something to do with JarikCoding's latest PR where it blocks "Unsafe LUA Functions".

Enabling it in players/user/config.cfg by changing set cg_enable_unsafe_lua_functions "0" to set cg_enable_unsafe_lua_functions "1" also did not work. I even changed the file to read only after changing that 1 variable and the issue persists.

I get the following errors below:

https://user-images.githubusercontent.com/118600360/222053759-57cb9889-0217-4bd5-95d4-b61de33e4686.mp4
<img width="1324" alt="Screenshot 2023-03-01 003459" src="https://user-images.githubusercontent.com/118600360/222053979-cf9d919f-e9dc-4ffb-80f9-f63f6444b0ad.png">
<img width="749" alt="Screenshot 2023-03-01 003530" src="https://user-images.githubusercontent.com/118600360/222054050-b245e11b-eef4-44e1-90d6-5c64fad2e1e0.png">

**Comment by momo5502** [comment]
I adapted the code to use the -unsafe-lua commandline argument instead

**Comment by momo5502** [comment]
the mod is still broken, but that's none of my business tbh
