### ISSUE TITLE
Ability to change the ui color from the default orange to whatever?

### ISSUE THREAD

**Issue by beanz69420** [momo5502/boiii#266]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

![Screenshot_20221225_145143](https://user-images.githubusercontent.com/126605011/222139328-0f61bc5c-c426-440d-b6bf-a39a69e2a44e.png)

**Comment by momo5502** [comment]
This is not planned. @shiversoftdev did this for zbr, but this is a lot of work and something a mod can do
