### ISSUE TITLE
another Arch Linux Bug dedicated server can't start because of "invalid host application"

### ISSUE THREAD

**Issue by hallinbirch** [momo5502/boiii#269]
### Bug Type

Dedicated Server

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Linux

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. put boiii.exe in dedicated server folder
2. run it from proton (or wine) with -dedicated flag
3.it  throws invalid host application error

### Expected Result

the server console to open

### Actual Result

a popup with invalid host application shows up instead then it closes

### (Optional) Proof and Additional Information

[steam-12469292733321707520.log](https://github.com/momo5502/boiii/files/10866887/steam-12469292733321707520.log)

### Severity/Priority

Minor

**Comment by momo5502** [comment]
you either have a corrupted dedicated server binary, or it's a leftover artifact from #262. Either way, this is fixed and you need to grab the original binary again.
