### ISSUE TITLE
Question: Does something like this exist for Black Ops 2?

### ISSUE THREAD

**Issue by Darthagnon** [momo5502/boiii#27]
Was wondering, do you know if something similar to this project exists for COD Black Ops 2? I remember there was [Redacted](https://redacted.se/), and possibly another server project who's name I forget.

Huh. Maybe Redacted is what I was looking for...

**Comment by momo5502** [comment]
We used to work on redacted, but got KIA. Meanwhile, there is plutonium. However, it is closed source, but it's based on our research from redacted.
