### ISSUE TITLE
ERROR failed to map blackops3,exe

### ISSUE THREAD

**Issue by BentleyOTF** [momo5502/boiii#271]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. i'll try to launch boiii then error
2. 
3. 

### Expected Result

It should Have the flie

### Actual Result

Blackops3,exe is not the flie

### Severity/Priority

High/Critical

**Comment by momo5502** [comment]
you're either launching it from a bad game directory or your game files are broken

**Comment by Ssj4justdale** [comment]
I also have this issue.  I haven't tested further but I'm thinking it pertains to my steam being downloaded on my C: drive and I have 2 library folders, one on my C: drive and one on my D: drive and my BO3 is on my D: drive.
