### ISSUE TITLE
Some bots do not use any weapons/Bots take up real player slots in Dedi

### ISSUE THREAD

**Issue by LevelChecker** [momo5502/boiii#275]
### Bug Type

Dedicated Server

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. Use sv_botsoak 1 in server.cfg to produce bots
2. enter game before they join, and you can see that some of the bots just use no weapon, fortunately atleast the bots are not all ruin using this
3. If you dont enter the lobby before the bots fill the server, it will kick you because the lobby is full even though they are bots.
![Screenshot_1](https://user-images.githubusercontent.com/57432637/222571269-4874472a-b2ec-48da-b1be-d5737a9068eb.png)

### Expected Result

Expected result:
Player joins lobby and kicks bot, either using maxaxis/maxallies or just botsoak
Bots use guns

I assume this might be them trying to use the default classes, in which case they are visible in the choose a class section but if you choose one, you get no weapons

### Actual Result

Result currently:
-Bots take up real player slots, if they fill the server, real players receive the message saying that the server is full and you cannot join
-Some bots do not use any guns, I am guessing it has to do with default classes not actually giving you guns but I can be wrong on that one.

### Severity/Priority

Medium

**Comment by JezuzLizard** [comment]
Bots should be taking up real player slots though. Do you mean when a real player attempts to join a bot should be kicked so the real player is able to join?

**Comment by LevelChecker** [comment]
> Bots should be taking up real player slots though. Do you mean when a real player attempts to join a bot should be kicked so the real player is able to join?
Yeah, either way if a server is 12/12 and you attempt to join, it wont kick a bot for an actual player
