### ISSUE TITLE
Adapt to the latest steam update

### ISSUE THREAD

**Issue by SwordSWD** [momo5502/boiii#277]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1.  Opening BOIII

### Actual Result

![image](https://user-images.githubusercontent.com/62721069/222787578-79161388-2ed7-4075-9e15-afa9090f52e9.png)

### Severity/Priority

High/Critical

**Comment by illnyang** [comment]
downgrade your game, latest update broke boiii

**Comment by illnyang** [comment]
it's so SHAMEFUL of them to update the game only after boiii got media attention, better late than never i guess

**Comment by momo5502** [comment]
> it's so SHAMEFUL of them to update the game only after boiii got media attention, better late than never i guess

That's a fact.

**Comment by momo5502** [comment]
#284
