### ISSUE TITLE
Playtime Counter

### ISSUE THREAD

**Issue by RyhZM** [momo5502/boiii#287]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

since play time doesnt cross over towards steam , it'd be cool to have your playtime tracked

**Comment by diamante0018** [comment]
This should be worked towards making sure the playtime is counted when Steam is opened rather than being it's on standalone thing.

**Comment by diamante0018** [comment]
Works here on Steam and on Steam Deck, are you sure of what you are saying?

**Comment by diamante0018** [comment]
I just confirmed steam is counting my hours on BO3 game while playing this client with Steam open.
I am gonna assume this may have been fixed on its own since you opened this issue.

**Comment by RyhZM** [comment]
> 

it now counts towards your playtime through steam. didnt back then

**Comment by Jxmbie** [comment]
My hours track but when I close and reopen steam, they go back to the time before I played.
