### ISSUE TITLE
Cilent/Server Index server mismatch during map_rotate. (Also map_rotate doubles?)

### ISSUE THREAD

**Issue by 4doorsmorehoes** [momo5502/boiii#293]
### Bug Type

Dedicated Server

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit), Windows Server 2019

### Reproducibility Rate

Medium: The bug can be reproduced intermittently

### Steps to Reproduce

Just run a server and join. Wait for the match to end.

### Expected Result
...
I believe we should connect fine after map_rotate? lol

### Actual Result

Seems it will rotate a map twice and on the last map rotate you will see a class menu then kicks you out with a crash with a message box of client/server index mismatch.
![image](https://user-images.githubusercontent.com/38188579/223503488-8644e2f1-8c6f-485a-97b0-1dd0e614ec1f.png)

### Severity/Priority

Med-high. might be annoying as shit to rejoin lol

**Comment by momo5502** [comment]
Seems fixed
