### ISSUE TITLE
"Fixing" killstreak sensitivity

### ISSUE THREAD

**Issue by January-0002** [momo5502/boiii#298]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

A simple idea in concept. 

Old CODs have the issue where on mouse, killstreaks have very limited maneuverability (best example is the dart).

A good QOL feature for a later time would be to normalize that sensitivity by 10-15% to a higher sensitivity, to allow M&K players to use killstreaks without breaking their elbows and wrists.

**Comment by momo5502** [comment]
Honestly, this sounds more like something a mod can do and nothing that should be done in the core code.
