### ISSUE TITLE
Download latest steam version

### ISSUE THREAD

**Issue by bstar16** [momo5502/boiii#299]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. open bo3 with boiii
2. client will ask to use latest steam version

### Expected Result

should just launch normally, i will note im not using steam bo3 so yeah not sure if it literally just needs to be updated.

### Actual Result

game doesnt launch with boiii

### (Optional) Proof and Additional Information

![image](https://user-images.githubusercontent.com/76526844/223679593-70e92a32-30b2-47a1-89ae-880d5674c578.png)

### Severity/Priority

Medium

**Comment by momo5502** [comment]
You obviously need to update

**Comment by bstar16** [comment]
ah ok was just checking to see because i cant update and it worked a few days ago even tho i was still using v100.0.0.0

**Comment by Echominium** [comment]
> ah ok was just checking to see because i cant update and it worked a few days ago even tho i was still using v100.0.0.0

are u using the cracked version if so then how did u update it because i cant find an updated version

**Comment by momo5502** [comment]
only steam bo3 is supported
