### ISSUE TITLE
Make dedi read gamesettings folder like Plutot6

### ISSUE THREAD

**Issue by 4doorsmorehoes** [momo5502/boiii#303]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

For example like PlutoT6 each exec tdm.cfg or dm.cfg will be on sv_maprotation with different scorelimit and timelimit settings.

https://github.com/xerxes-at/T6ServerConfigs/tree/master/localappdata/Plutonium/storage/t6/gamesettings

**Comment by diamante0018** [comment]
Can you clarify for me how it works on plutonium?
It's not clear to me if it's automatically exec'd from code depending on the game mode or if the game mode specific xff is added by the user in the sv_maprotation dvar.
