### ISSUE TITLE
g_log_filename support

### ISSUE THREAD

**Issue by 4doorsmorehoes** [momo5502/boiii#304]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

Seems g_log doesn't support from the server.cfg. This will be nice to have in case someone hosting more then 1 dedicated server.

**Comment by diamante0018** [comment]
g_log is hardcoded right now. It has the default game behaviour. Until the dvars are unlocked it could be set from the command line otherwise I see this almost as a non issue

**Comment by diamante0018** [comment]
https://github.com/momo5502/boiii/blob/main/src/client/component/game_log.cpp#L47

**Comment by Brentdevent** [comment]
Perhaps instead of hardcoding the name it should be taken from the dvar `log_filename`?
