### ISSUE TITLE
KN-44 Weaponized 115 camo bug?

### ISSUE THREAD

**Issue by sami4j1** [momo5502/boiii#309]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. On the KN-44 in zombies weapon kits.
2. 
3. 

### Expected Result

Covers the main gun part.

### Actual Result

Doesn't cover the whole gun

### (Optional) Proof and Additional Information

![image](https://user-images.githubusercontent.com/107014555/223881080-9e8c6c8b-b7d7-4c89-84cb-cb4a1d98d216.png)

### Severity/Priority

High/Critical

**Comment by sami4j1** [comment]
This isnt critical, my mistake for tagging it as that.

**Comment by SwordSWD** [comment]
This isnt an issue or bug. This is in the original game too
![RDT_20230308_1915104601291239290785555](https://user-images.githubusercontent.com/62721069/223882265-8e24c807-5388-47fe-9ac8-c9532a7b1b81.jpg)

**Comment by momo5502** [comment]
Can be done through a mod, but it's nothing that we should take care of
