### ISSUE TITLE
Steam Input does not work

### ISSUE THREAD

**Issue by OceanMV** [momo5502/boiii#315]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. Launch BOIII
2. Connect a controller that works via SteamInput (in my case a PS5 controller)
3. Attempt to apply any input (buttons, triggers, thumbsticks)

### Expected Result

What should happen is that once the controller is connected via Steam, inputs should be recognized from the controller.

### Actual Result

Nothing happens at all.

### (Optional) Proof and Additional Information

I'm able to reproduce the issue from both the menus and ingame. I've also attempted to connect the controller _before_ opening BOIII, with no luck.

### Severity/Priority

Medium

**Comment by momo5502** [comment]
You should launch boiii via steam by adding it as non-steam game, I bet.

**Comment by OceanMV** [comment]
Yeah, guess I thought it was already hooked onto it since it showed in the steam status. Thanks man, loving this mod so far!
