### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Xepster** [momo5502/boiii#316]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. Open the game

### Expected Result

The game doesn't crash when opened.

### Actual Result

The game crashes when opened.

### (Optional) Proof and Additional Information

Latest steam version. Crash always happens just after the intro movie, if the intro movie is skipped it will happen sooner. Approx. 1 second after the main menu screen appears.

[boiii-crash-2023-03-10-19-50-19.zip](https://github.com/momo5502/boiii/files/10947116/boiii-crash-2023-03-10-19-50-19.zip)

### Severity/Priority

High/Critical

**Comment by Xepster** [comment]
Executing boiii.exe as admin one time fixed the problem for me.

**Comment by diamante0018** [comment]
This issue is closely related to: https://github.com/momo5502/boiii/issues/514#issuecomment-1507307604

**Comment by AoElite** [comment]
Having the same issue on Windows 10, even running as administrator doesn't fix the issue

**Comment by momo5502** [comment]
You guys likely have broken game files. 
Also, running BOIII as admin is never going to fix anything. BOIII is not supposed to be run as admin.

**Comment by diamante0018** [comment]
No further reply from OP received, assuming broken game files.
