### ISSUE TITLE
Console Error: Invalid line in playlist

### ISSUE THREAD

**Issue by WantedDV** [momo5502/boiii#318]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1.  start boiii and watch console output

### Expected Result

These functions get the name and description of game modes to display in the menus in the correct language.

### Actual Result

Lines of **playlists_tu32.gz** using `nameref ` and `descriptionref ` instead of `name` and `description `are throwing errors in the console on startup.

`Error: line 1497: Invalid line in playlist 1`
```
line 1497: nameref PLAYLIST_PLAYLIST_TDM
line 1498: descriptionref PLAYLIST_PLAYLIST_TDM_DESC
```

### (Optional) Proof and Additional Information

These functions _seem to work_ fine despite giving an error, but I thought I would report in case this ends up causing other problems. 

### Severity/Priority

Minor

**Comment by momo5502** [comment]
Doesn't cause any issues to my knowledge. Playlists are not supported anyways.
