### ISSUE TITLE
Enable offline matchmaking 

### ISSUE THREAD

**Issue by joseupp** [momo5502/boiii#32]
It would be possible to enable offline local matchmaking to play alone against bots and be able to level up.
Currently I have modified the clients s1x, iw6x, iw4x, pluto - t6 to be able to play alone, modifying the playlist so that the bots connect and can start the games.
But in t7 it does not work, according to the console when you search for a game the error appears ( DW lobby: missing service 21).
![Sin título](https://user-images.githubusercontent.com/108338623/193408194-9ba85862-988c-49f5-a5af-48f4acf50d3f.png)

**Comment by Postalityjr-hub** [comment]
May I ask how you managed to enable local matchmaking? really interested for T6 for me and my family if its possible

**Comment by joseupp** [comment]
> May I ask how you managed to enable local matchmaking? really interested for T6 for me and my family if its possible

https://github.com/joseupp/t6-offline-MatchMaking

**Comment by joseupp** [comment]
> May I ask how you managed to enable local matchmaking? really interested for T6 for me and my family if its possible

Check out my github profile

**Comment by 4doorsmorehoes** [comment]
> > May I ask how you managed to enable local matchmaking? really interested for T6 for me and my family if its possible
> 
> Check out my github profile

might want to remove that paypal link and your config.json unless you want people playing your account and get banned.

**Comment by NotAdamGamingLOL** [comment]
How did you get access to Public Match with a mod loaded? I've tried everything I could think of but got no luck.

**Comment by joseupp** [comment]
> ¿Cómo obtuviste acceso a Public Match con un mod cargado? He intentado todo lo que se me ha ocurrido, pero no he tenido suerte.

It is a personal mod for testing, it is not public.

**Comment by joseupp** [comment]
> > > May I ask how you managed to enable local matchmaking? really interested for T6 for me and my family if its possible
> > 
> > 
> > Check out my github profile
> 
> might want to remove that paypal link and your config.json unless you want people playing your account and get banned.

Thanks

**Comment by Postalityjr-hub** [comment]
Thanks a ton man I'm gonna check it out when I get home from work, does it work LAN or is it single player only?

> > May I ask how you managed to enable local matchmaking? really interested for T6 for me and my family if its possible
> 
> 
> 
> Check out my github profile

**Comment by joseupp** [comment]
> Thanks a ton man I'm gonna check it out when I get home from work, does it work LAN or is it single player only?


You can play on Lan using the console and the command connect xxx.xxx.x.x, the x are the ip address of the host, connect once the lobby is created.

**Comment by Postalityjr-hub** [comment]
oh shit I think I meant IW6X not T6, do you have that by chance man?

**Comment by momo5502** [comment]
Is this still relevant?

**Comment by joseupp** [comment]
> Is this still relevant?

This already really works, the only thing missing is for it to work automatically, I don't know if it's feasible to patch so that the game believes that there is 1 game and players and thus start the process and launch the game. Is it possible to do this? In previous games just having party_minplayers 1 worked but not in this one.
