### ISSUE TITLE
Maximum amount of players on Zombie Dedis is 3

### ISSUE THREAD

**Issue by Dss0** [momo5502/boiii#324]
### Bug Type

Dedicated Server

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Windows Server 2019

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. Start a zombies dedi
2. Have 4 players try to join it

### Expected Result

4 Players can play on it

### Actual Result

Error message saying "server is full" displayed after there are 3 people on the server.

### (Optional) Proof and Additional Information

I assume this may be because the dedi is counted as a client.

### Severity/Priority

Medium

**Comment by Zedator1** [comment]
what is a dedi

**Comment by Dss0** [comment]
a dedicated server..
