### ISSUE TITLE
Unable to use premium sugar

### ISSUE THREAD

**Issue by liveskai** [momo5502/boiii#326]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

Premium sugar is optional and not available in the game

### Expected Result

Use

### Actual Result

Use

### (Optional) Proof and Additional Information

![image](https://user-images.githubusercontent.com/54350655/224547836-86af5bbd-6113-4a11-b6d5-e20ed8a5c6d9.png)

### Severity/Priority

High/Critical

**Comment by Dss0** [comment]
An issue already exists for this: https://github.com/momo5502/boiii/issues/203
