### ISSUE TITLE
Support 3 char names

### ISSUE THREAD

**Issue by 4doorsmorehoes** [momo5502/boiii#327]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

Would be nice to have /name Fry 

![boiii_2023-03-12_10-46-03](https://user-images.githubusercontent.com/38188579/224553400-bbcea765-c18c-41f7-aeb7-8a8e7b82353a.png)

**Comment by supitsmike** [comment]
#366

**Comment by 4doorsmorehoes** [comment]
Thanks
