### ISSUE TITLE
Game hangs on startup. Possible Nvidia issue.

### ISSUE THREAD

**Issue by WantedDV** [momo5502/boiii#333]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

Low: The bug has only occurred once or a small number of times

### Steps to Reproduce

There is a issue during startup that causes it to hang when it gets to the loading of gsc part. The only thing I did to cause this issue was let my pc sleep overnight and attempt to reopen the game the next morning.

I can guarantee this is not a file issue because the first thing I did was verify files and try to start the game on latest unmodified boiii. 

I actually think this is a Nvidia issue; the solution was to reboot my pc and when I did Windows Shutdown prompted me that a program was still open `nvContainer....`. 

Everything worked fine after a reboot.

### Expected Result

boot completely

### Actual Result

It doesn't become unresponsive or anything, it just doesn't ever finish booting. 

### Severity/Priority

Minor

**Comment by momo5502** [comment]
If the game hangs, I need a memory dump. otherwise there is nothing i can analyze.

**Comment by momo5502** [comment]
Closing it for now. feel free to reopen if it occurs again, but next time please provide a memory dump
