### ISSUE TITLE
Rcon commands say and tell do not work 

### ISSUE THREAD

**Issue by SwordSWD** [momo5502/boiii#341]
### Bug Type

Dedicated Server

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Windows Server 2019

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. Run IW4MAdmin or use an rcon command prompt like icecon
2. Run a command like !help or say in iceon

### Expected Result

Output like this.
![image](https://user-images.githubusercontent.com/62721069/225161477-9706060a-8c55-4190-a398-5f4b8919014f.png)
Before the new chat update.

### Actual Result
![image](https://user-images.githubusercontent.com/62721069/225162555-3752fd38-1ecc-4c07-99fc-d99b5e781971.png)
After the new chat update.

### (Optional) Proof and Additional Information

Also tried using icecon but showed no response 
![image](https://user-images.githubusercontent.com/62721069/225161784-8c3c92af-2875-4304-9b4e-4d566992b4ca.png)

### Severity/Priority

Minor

**Comment by alnoisegit** [comment]
Same thing, and I'm also running multiple servers. Someone was able to get it working running a single server so it might have something to do with how logging is done while multiple servers are running.

**Comment by SwordSWD** [comment]
IW4MAdmins new commits fixed the Multiplayer output. However, There is no output for zombies. Simply because there is no killfeed window.

**Comment by SwordSWD** [comment]
![image](https://user-images.githubusercontent.com/62721069/227123897-24e68819-2488-4418-a6f9-6f0e8c3de9d8.png)
![image](https://user-images.githubusercontent.com/62721069/227123999-c4e96aea-ae19-49c3-a54c-b23db88c07c4.png)

say duplicates output but there is no tell output

**Comment by momo5502** [comment]
> I would like an update on the issue, thanks

i don't. everything is clear for me here. i'm currently working on it.

**Comment by momo5502** [comment]
> 

that is an iw4madmin bug.

**Comment by momo5502** [comment]
https://github.com/momo5502/boiii/commit/ab8d41f209690229a657aa9c5d25814b2553d92d

**Comment by SwordSWD** [comment]
> > say duplicates output but there is no tell output
> 
> duplicate output is an iw4madmin bug. i probably goofed tell. will check. will try to move it from the killfeed back to the chat, then it should be working in zombies.

I did not use iw4madmin for say. I used ICECON

**Comment by diamante0018** [comment]
Pending #383 and an update from IW4M parser (deletion of the override for chat Regular expression) this issue shall be fixed most likely.
