### ISSUE TITLE
How to change default language ?

### ISSUE THREAD

**Issue by Warlockhome** [momo5502/boiii#346]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

i need change language from russian to chinese, and i cant find the option to change language in game
also
i cant launch game by boiii if i change the file(location？.txt)

**Comment by momo5502** [comment]
Should be done using steam. Nothing we address. You need the proper game files for your language.
