### ISSUE TITLE
in zombies mode only the host can buy gobblegum,other clients can't

### ISSUE THREAD

**Issue by zzyGodofWar** [momo5502/boiii#353]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

Host started privated zombies game other players join by type "connect IP" in console , in game only the host can buy gobblegum,other clients can't

### Expected Result

other players(clients) should buy gobblegum correctly

### Actual Result

but when they buy gobblegum, the gobblegum turns white

### Severity/Priority

High/Critical

**Comment by momo5502** [comment]
#203
