### ISSUE TITLE
All Input is invalid,and Had problems switching between full screen and Windows

### ISSUE THREAD

**Issue by zzyGodofWar** [momo5502/boiii#354]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

It's easy to run into these problems,see the following

### Expected Result

offen got black screen after CG 
sometime the mouse and keyboard can't control the game,only cursor work,other input is invalid
Use ALT + ENTGER to switching between full screen and Windows may make game Glitch

### Actual Result

problem1:offen got black screen after CG 
the console show and block
execing gamedata/configs/common/thumbstick/default.cfg from fastfile
Client: Registering configstring index 3241 with data yE痲?
Client: Registering configstring index 3241 with data yE痲?

problem2:sometime the mouse and keyboard can't control the game,only cursor work,other input is invalid

problem3:Use ALT + ENTGER to switching between full screen and Windows may make game Glitch

### Severity/Priority

High/Critical

**Comment by diamante0018** [comment]
Can't repro.
