### ISSUE TITLE
/name command not changing name

### ISSUE THREAD

**Issue by onedollarplutonium** [momo5502/boiii#359]
### Bug Type

Other

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. open the console 
2. type "/name blah blah"
3. press enter

### Expected Result

name change

### Actual Result

name doesnt change from unknown soldier

### Severity/Priority

Minor

**Comment by momo5502** [comment]
you have to restart your game after changing your name
