### ISSUE TITLE
Typo in gamesettings_escort.cfg

### ISSUE THREAD

**Issue by WantedDV** [momo5502/boiii#361]
### Bug Type

Client, Dedicated Server

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

Line 12 of gamesettings_escort.cfg
`gaemtype_setting`

### Expected Result

plz how fix gaem??

### Actual Result

gaemtype_setting

### Severity/Priority

Minor

**Comment by diamante0018** [comment]
Where would this file be?
