### ISSUE TITLE
Client game settings are not set properly when joining a server

### ISSUE THREAD

**Issue by WantedDV** [momo5502/boiii#362]
### Bug Type

Client, Dedicated Server

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Problem
The clients game settings are not being set correctly for dedicated servers. This will cause problems like:
1. incorrect scoreboard when trying to join a non-team mode after joining a team one https://github.com/momo5502/boiii/issues/255
2. joining a server with class restrictions causes any subsequent games to have the same restrictions
3. Invisible weapons
4. Incorrect load screens and wrong or missing text
...

### Solution
If server hosts intend on using config files to manage servers then we need a way to properly load and unload game settings before joining the server.

- [partial working] using `gametype "gun";connect ip:port` fixed the scoreboard issue. Although it can sometimes have problems like incorrect text and invisible weapons.
- [working] going into a public lobby and selecting the **same** game mode as the server correctly sets the proper gamesettings. This fixes all the issues mentioned above! Unfortunately players do not have access to all game modes without https://github.com/momo5502/boiii/pull/328 so they will not be able to use this workaround. 

Here is the [server.cfg](https://github.com/momo5502/boiii/files/11009981/server.cfg.txt) that I used for testing. It works with gungame and Blackjacks gungame. Remove the .txt from the extension. Github wouldn't let me upload a cfg.

### Expected Result

.

### Actual Result

.

### (Optional) Proof and Additional Information

It is possible that dedicated servers set up to run via the [playlist method](https://steamcommunity.com/sharedfiles/filedetails/?id=814090509) would resolve this automatically, but I have not been able to get them running to test with boiii.

As this is not a issue for public games accessed through the lobby system, it might helpful to look at `\lobbyRunPlaylistSettings` to see how lobbies sets/unset game settings based on what mode is selected, and try to do something similar for configs.

I am reluctant to set this as critical but this issue seems to stem into multiple other issues and could affect all game modes and servers.

### Severity/Priority

High/Critical

**Comment by momo5502** [comment]
Shouldn't this be fixed with this: #382 ?

**Comment by Brentdevent** [comment]
Yea, #382 and #388 fixes all these issues mentioned here.
