### ISSUE TITLE
Real player count in game ? 

### ISSUE THREAD

**Issue by Stormiswe1** [momo5502/boiii#369]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

Hi so recently @ Future on discord sended this link https://master.xlabs.dev/stats.json and it give me an idea 

Basically It only says the "real" number of players in each game so i was wondering if it could be possible to implement the real player count in boiii moslty for the muliplayer because : 

- It could avoid having to join each server to be sure that no one is online due to bots counted as players (this don't happen in zombie) 

Thanks

**Comment by momo5502** [comment]
just like the effective player count in iw4x

**Comment by mjkzy** [comment]
![image](https://user-images.githubusercontent.com/64374267/226467899-e354dab1-54a6-43d6-926e-bf64239d2a31.png)
on our h1-mod, our solution was to just show the overall real player count in the `2/18` thing, with "2" being the real players, and then we put the overall clients (clients + bots) in the `[5]`
so it looked like `2/18 [5]`, meaning 2 real players were in the game and 5 real players and bots were in the game. of course, this doesn't entirely make sense, but it's just a idea

**Comment by Stormiswe1** [comment]
I don't know if you were answering to me but that could be very useful even more than just having a player count without knowing in which server they are

**Comment by mjkzy** [comment]
> I don't know if you were answering to me but that could be very useful even more than just having a player count without knowing in which server they are

the solution listed above is information showed on a server. a overall player count in all of the client could be cool, but i think you can get that same information from the server browser too

**Comment by diamante0018** [comment]
Looks like from code it's implemented in boiii but it's missing the lua menu modification.
