### ISSUE TITLE
Crashing at launch

### ISSUE THREAD

**Issue by SousaSoftware** [momo5502/boiii#37]
Crashing at launch. Using latest Steam files
[https://i.postimg.cc/7ZgXJzpK/image.png](url)

Seems like a fix was tried to fix this, but its still happening, i hope the attached minidump file will help sorting the problem
[boiii-crash-2022-10-01-18-50-22.zip](https://github.com/momo5502/boiii/files/9690891/boiii-crash-2022-10-01-18-50-22.zip)

Thanks for working on this

**Comment by momo5502** [comment]
Can you please verify if the latest fix works for you?

**Comment by SousaSoftware** [comment]
> Can you please verify if the latest fix works for you?
Unfortunately, it keeps happening. Attached the new minidump file

[boiii-crash-2022-10-01-19-31-51.zip](https://github.com/momo5502/boiii/files/9690948/boiii-crash-2022-10-01-19-31-51.zip)

**Comment by momo5502** [comment]
Nvm, i can still reproduce it.

**Comment by momo5502** [comment]
Can you try again please

**Comment by SousaSoftware** [comment]
> Can you try again please

This seems to be fixed now. Thanks for looking into it

**Comment by momo5502** [comment]
Perfect, thank you for reporting it.
