### ISSUE TITLE
MOD archives always get reset

### ISSUE THREAD

**Issue by liveskai** [momo5502/boiii#371]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

MOD archives always get reset

### Expected Result

Unable to keep mod archives

### Actual Result

Unable to keep mod archives

### Severity/Priority

High/Critical

**Comment by momo5502** [comment]
what the hell is mod archives?

**Comment by liveskai** [comment]
> what the hell is mod archives?

![image](https://user-images.githubusercontent.com/54350655/226854737-669080b5-752c-43bd-be69-caad8cce613a.png)

**Comment by Dss0** [comment]
it's still unclear what you're trying to do. Are you trying to use stats files you got from somewhere and they don't save? I also don't understand where those folders come from. Normally the mod-specific stats are saved in players/mods/modname.

**Comment by shiversoftdev** [comment]
> it's still unclear what you're trying to do. Are you trying to use stats files you got from somewhere and they don't save? I also don't understand where those folders come from. Normally the mod-specific stats are saved in players/mods/modname.

Mod-specific stats from mods downloaded from workshop go to this directory "players/311210/<mod_id>".

**Comment by diamante0018** [comment]
I think the OP got a good explanation from shiversoftdev.
