### ISSUE TITLE
Let players be able to join a private game lobby.

### ISSUE THREAD

**Issue by LigmuhBOLLZ** [momo5502/boiii#372]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

I believe it is not ideal for everyone that just wants to play a private game especially in zombies to have to put in /connect ip:port and all of that its very tedious. Not a fan of servers either with my ip and whatnot being open to the public. Please have some sort of miracle and let us have an easier way to join a friend's game. Or you could let us be able to join a friends lobby so that we can all start games at the same time. Pretty sure there are a few maps that break cause of people not loading into the map at the same time.

**Comment by LigmuhBOLLZ** [comment]
If it aint possible it is what it is I guess 💀

**Comment by mjkzy** [comment]
unless a DW server is emulated, that is the only way to kinda bridge a friends list and such together

**Comment by momo5502** [comment]
Your IP adress is inherently public. It is not a secret. People have to stop believing it is.

**Comment by momo5502** [comment]
You're pretty much requesting the friends list, which already exists as an issue.
