### ISSUE TITLE
Command line thing

### ISSUE THREAD

**Issue by EverlastingInsomnia** [momo5502/boiii#373]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. Launch BOIII
2. Click Play
3. Nothing in console happens expect "command line:"

### Expected Result

nothing happens, the console just close

### Actual Result

Console just closing, and i dont see any errors

### (Optional) Proof and Additional Information

![image_2023-03-22_140122145](https://user-images.githubusercontent.com/128577194/226826159-716e6038-2b85-477e-86d1-f71766b5cc6c.png)

### Severity/Priority

Medium

**Comment by EverlastingInsomnia** [comment]
Oh, error 
![Uploading image_2023-03-22_140233689.png…]()

**Comment by EverlastingInsomnia** [comment]
> upload the dump

here

**Comment by EverlastingInsomnia** [comment]
So, what is it?

**Comment by momo5502** [comment]
Has nothing to do with boiii. It's either broken game files or an issue with your system. make sure to install all windows updates and get proper game files and not something from: 
`Торренты\Call of Duty - Black Ops 3 (2015) Portable by Canek77`
