### ISSUE TITLE
BOIII is not building in Visual Studio.

### ISSUE THREAD

**Issue by linklel11** [momo5502/boiii#377]
### Bug Type

Other

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

Build in VS.

### Expected Result

Should build

### Actual Result

errors

### (Optional) Proof and Additional Information

![image](https://user-images.githubusercontent.com/77317219/227043242-e3883d57-8298-4df8-b4a2-2f705a7b65d3.png)

### Severity/Priority

Medium

**Comment by 4doorsmorehoes** [comment]
How did you git clone? mine works perfectly on Visual Studio 2022

**Comment by linklel11** [comment]
it's most likely update 
![image](https://user-images.githubusercontent.com/77317219/227046772-4f053a04-07ab-4feb-af20-f5e734d27ac6.png)
as it updated a toolset. i just built this on the 20th no issues. i pulled a bunch of changes today (15) and it wouldnt build.
but i git cloned it from the vs tab
![image](https://user-images.githubusercontent.com/77317219/227047018-f8faa99e-1499-48e6-b92a-8cb37e6fc66e.png)

**Comment by diamante0018** [comment]
You need to click rebuild all to fix that error in the build section.
you updated visual studio prior to getting that error.
Also just reading the error message and googling it could you have brought you to the same conclusion.

**Comment by linklel11** [comment]
i'm new to VS so i didn't know that it wouldn't just auto update that file with the new information.
and you are correct i did just install the update today.
p.s sorry for any inconvenience i have caused today. <3
