### ISSUE TITLE
g_inactivity support

### ISSUE THREAD

**Issue by 4doorsmorehoes** [momo5502/boiii#378]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

Would be nice to stay on the server regardless of what time your g_inactivity and g_inactivitySpectator set to

**Comment by diamante0018** [comment]
if you set it to 0 doesn't it allow you to stay for an infinite amount of time?
