### ISSUE TITLE
Custom zombies map support on dedicated servers.

### ISSUE THREAD

**Issue by espenshadow** [momo5502/boiii#380]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

Map/Asset modding is the heart and soul of the zombies community. Currently, after a few days of troubleshooting through trial and error, it appears only possible to host and join multiplayer servers running the standard map rotation. Custom map support would be a significant feature to the service.

If there's third party support capable of supporting this feature, or something that spans beyond my knowledge/capabilities, shedding light on any solutions would be monumental for the layman community regardless.

**Comment by Dss0** [comment]
This works already, you have to put the map into the "usermaps" folder on your server. However the client has to have the map already installed to be able to join so automatically downloading maps from the steam workshop or via fastdl is what's missing here.

**Comment by espenshadow** [comment]
Strange. I should instead open a bug ticket for the four of us instead. I apologize. When attempting to join the server from the client with files present in usermap>workshopfoldername>zone we get the Error: Could not find rawfile "gamedata/constbaselines/zm/bl_little_endian_core_frontend_frontend.bin" / "Could not load level fastfile for level 'map_name' could not read fastfile (null)"

https://imgur
[boiii-crash-2023-03-22-16-20-20.zip](https://github.com/momo5502/boiii/files/11045513/boiii-crash-2023-03-22-16-20-20.zip)
.com/zLa6TcM

However the map can be played when simply starting a private match.

If the map files from the client are placed in >zone, the error is instead: (zm_der_riese) exceeded: too many asset overrides in one call to DB_LoadXAssets.

https://imgur.com/O6Ht5HG
