### ISSUE TITLE
Movie Making and cinematics

### ISSUE THREAD

**Issue by SinOfHyped** [momo5502/boiii#391]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

Hi, I have been following the BOIII development scene for a bit, and I just want to say phenomenal work.
However, I wanted to request some features for the creative side that could emerge from this client.

Theres this tool called Airyz BO3 tool. That allows you manipulate demos so you can add fog, adjust fov sliders, remove gun model from clips, a advanced dollycam that allows for rotation/ fov and a bunch of movie-making sliders.

I wanted to ask if this could be integrated into the client, where you can record depth, greenscreen, world clips right inside the client. and same for cinematic shots and povs as well. (kinda like HLAE for CSGO)

Or at the very least, make sure airyz bo3 editing tool works in the client and the cheat detection disallows its use (its only job is client-side manipulation of theatre mode/demos, so it is safe)

Thank you,
Sin
https://www.youtube.com/watch?v=l7pG7c6BXdI&ab_channel=TrackzVFX
(the bo3 editing tool can be found in the team A discord server, under the presents channel)

**Comment by diamante0018** [comment]
I don't think it's a good idea to integrate other projects into this client. I suggest you use this mod on the original bo3 if it's not compatible somehow with boiii

**Comment by Airyzz** [comment]
Hey y'all, I made that tool! I will say now if boiii gets theater mode support I will make sure the tool supports it

**Comment by SinOfHyped** [comment]
> I don't think it's a good idea to integrate other projects into this client. I suggest you use this mod on the original bo3 if it's not compatible somehow with boiii

Or you can integrate it with theatre mode itself (have a own version like built in) if you plan to have one on the client. And beside that, does that mean the possibility of reshade also not being supported?

**Comment by diamante0018** [comment]
> Hey y'all, I made that tool! I will say now if boiii gets theater mode support I will make sure the tool supports it

Thanks. It will be best to leave the two separate I think. In the past I believe iw4x used to have something similar but it was later removed from the client for various reasons including it had memory leaks. I don't think it's a good idea to mix such a specific project with boiii as at best it would only be used by few people.

**Comment by diamante0018** [comment]
As nothing else was added, I'll trust the promise from the creator that this tool will be compatible with boiii client. if you have any issue with doing so when this client is released feel free to contact us.

**Comment by iamquty** [comment]
would be nice if we could use the theater with custom maps (if it's possible of course)
