### ISSUE TITLE
dlc maps not working

### ISSUE THREAD

**Issue by Kuwari9** [momo5502/boiii#397]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. i downloaded the dlc file u pinned in the chat section. and followed the steps
2. These are the DLCs for T7, for people who own the game on Steam but don't want to pay a ridiculous amount of money for the DLCs.
This will also be useful after the ownership check has been re-enabled.

and whenever i chose a dlc map and start it immediately kicks me and gives me this error ERROR: Could not find zone 'ea_zm_castle_patch'
3. 
4. 

### Expected Result

![Capturefrefe](https://user-images.githubusercontent.com/128872861/227749021-6d7ac8fd-0c01-418b-8dc6-7517a685754f.PNG)

### Actual Result

ERROR: Could not find zone 'ea_zm_castle_patch'

### Severity/Priority

High/Critical

**Comment by 4doorsmorehoes** [comment]
DLC works fine for everyone...Can you confirm en_zm_castle_patch.ff is in your zone folder?

**Comment by diamante0018** [comment]
You should resolve support issues in the server you got that link from. This appears to not be an issue with the client.
