### ISSUE TITLE
error emulating servers

### ISSUE THREAD

**Issue by anyamew** [momo5502/boiii#399]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. 
2. 
3. 

### Expected Result

when i start the game it gives me an error

### Actual Result

when i start the game it gives me an error

### (Optional) Proof and Additional Information

![image](https://user-images.githubusercontent.com/63223344/227773255-84859ae6-fd03-4881-b033-782871bd7f71.png)

### Severity/Priority

High/Critical

**Comment by diamante0018** [comment]
Can you translate that error message? Does it say you are not connected to the internet?

**Comment by momo5502** [comment]
probably broken game files. or not running the game with boiii.

**Comment by diamante0018** [comment]
I thought so too, as I asked the user to clarify already 2 days ago but not got a reply I think it's fair to say in 5 days we will close this issue without a response

**Comment by diamante0018** [comment]
No response.
