### ISSUE TITLE
Support joining pre-game lobby in main menu

### ISSUE THREAD

**Issue by Airyzz** [momo5502/boiii#405]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

It would be very convenient to be able to join (via lan or p2p, this probably isnt relevant for dedi) the pre game lobby similarly to in the base game. This is useful for private matches and zombies, when you might want to back out of the game to adjust game rules or change zombies map. 

It would also be nice not having to have already started the match for people to be able to join, which creates a strange user experience, especially so in zombies where there are some important things which can occur during the very start of the game, such as on Moon (area 51 spawn)

**Comment by momo5502** [comment]
nope. lobby system has been removed on purpose as it's full of vulnerabilities

**Comment by Airyzz** [comment]
Is it possible we can reconsider this, as removing the lobby system seems to break some custom maps with custom intro sections?

**Comment by momo5502** [comment]
> nope. lobby system has been removed on purpose as it's full of vulnerabilities

nope. lobby system has been removed on purpose as it's full of vulnerabilities

**Comment by Airyzz** [comment]
> > nope. lobby system has been removed on purpose as it's full of vulnerabilities
> 
> nope. lobby system has been removed on purpose as it's full of vulnerabilities

I understand that, but I think its worth atleast discussing alternatives before dismissing it outright. 

I think this will cause more issues in the zombies mode, especially for easter eggs which require a certain number of players, such as Shadows of Evil.

 iirc some of these maps check for certain conditions when the game starts, and if you dont have the right number of players at the start of the game, certain things won't work later, even if the correct number of players have joined the game by that point

I think not being able to complete the main quest of a base game map is a very significant regression regression and is atleast worth discussing
