### ISSUE TITLE
Name change is not working for me.

### ISSUE THREAD

**Issue by BndoBsic03** [momo5502/boiii#406]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. 
2. 
3. 

### Expected Result

I open the game and do /name and expect my name to change after i reset my game

### Actual Result

After the game restart, My name is the exact same nomatter what i do

### Severity/Priority

Minor

**Comment by momo5502** [comment]
What is the name you are trying to apply? Can you check %localappdata%/boiii/user there should be a json file somewhere. please show the contents of that file.

**Comment by diamante0018** [comment]
No response was given. Closing. If OP reads this, he is advised to track progress of #300 
Dynamic names changes are not yet supported.
