### ISSUE TITLE
Auto launch launcher!

### ISSUE THREAD

**Issue by JayEdgarMaggio** [momo5502/boiii#407]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

First of all, I just wanted to say thank you for the fantastic work! I'm really enjoying it. This is exactly what this game needed.
Now I was just wondering if there was a way to make the launcher self-launch or at least have the PLAY button ready for an enter command. The reason for this is that I would like to add the game to my RetroFe frontend and it has to be runnable from a bat file without mouse inputs.

Example:
@echo off
start pressenter.vbs (this will press Enter in case it's possible)
set "GAMENAME=boiii.exe"
set "GAMEPATH=\%~n0\"
set HOME="%~dp0"
set "GAMEROOT=%~dp0%GAMEPATH%"
cd %GAMEROOT%
start "" /WAIT "%GAMEROOT%%GAMENAME%"
exit

**Comment by 4doorsmorehoes** [comment]
Try boiii.exe -multiplayer

**Comment by 4doorsmorehoes** [comment]
Try boiii.exe -launch

**Comment by JayEdgarMaggio** [comment]
> Try boiii.exe -launch

Works perfectly, thank you!

New working bat in case someone needs it.

@echo off
set "GAMENAME=boiii.exe"
set "GAMEPATH=%~n0"
set HOME="%~dp0"
set "GAMEROOT=%~dp0%GAMEPATH%"
cd %GAMEROOT%
start "" /WAIT "%GAMEROOT%%GAMENAME%" -launch
exit
