### ISSUE TITLE
Allow equipping multiple of the same gobblegum

### ISSUE THREAD

**Issue by ItsCharaHere** [momo5502/boiii#408]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

pretty self explanitory, make equipping multiple of the same gobblegum, or only a select few gobblegums (2 or 3) possible instead of forced having 5 gobble gums. (One use case would be equipping 5 of the "Random" gobble gums to have a completely random gobblegum deck in game)

**Comment by zzyGodofWar** [comment]
but the impotant thing is the gobblegum have a big problem in co-op game,only the host can buy Mega gobblegum,other will show "Out of ..."

**Comment by diamante0018** [comment]
This falls under the category of game mods.
Meaning this should be possible by making a mod. Maybe the mod can be as simple as editing the GSC file that handles this logic.
I don't think boiii should modify the stock game behaviour in favour of your personal preference.
In short, please make a mod to achieve your desired effect.
