### ISSUE TITLE
The error I appeared

### ISSUE THREAD

**Issue by wujingshen** [momo5502/boiii#409]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. just click the launcher
2. 
3. 

### Expected Result

maybe it   normal running 

### Actual Result

Open the launcher, it says Can't access this web page and make sure the web address is correct

### Severity/Priority

High/Critical

**Comment by momo5502** [comment]
can you type this in your cmd and make a screenshot: `echo %localappdata%`

**Comment by wujingshen** [comment]
Thanks for your advice，I've uninstall this when I find it doesn't work and bought a genuine one.But I want to know why，I will download it again.So，what screenshot you want to get .
![IMG_20230330_234652](https://user-images.githubusercontent.com/98304276/228996409-e55319ab-9238-4289-afc0-830f3165d4dc.jpg)
![IMG_20230330_234851](https://user-images.githubusercontent.com/98304276/228996478-f850c1d5-a16f-4b97-984a-e54c8895812a.jpg)

**Comment by wujingshen** [comment]
oh yes， it run normal when I close the firewall，very thanks.
