### ISSUE TITLE
Devmap and Custom MP maps cannot load their fastfiles

### ISSUE THREAD

**Issue by January-0002** [momo5502/boiii#410]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

Step 1) try download any multiplayer map
Step 2) try to open said map in custom games (usermaps loads successfully as a mod)
Step 3) map will either not load or fully error out, telling that the fastfile cannot be read.

FOR DEVMAP

Step 1) try to run any devmap
Step 2) a hexadecimal error pops up and the map does not load

### Expected Result

Maps load fine

### Actual Result

Maps do not load, as described in the "steps to reproduce" tab.

### Severity/Priority

Medium

**Comment by momo5502** [comment]
that sounds like an issue with the mod/map you are trying to load.

**Comment by January-0002** [comment]
Yep that works.

To expand, this is using the tutorial above, just in a lot more detail for the newbies.

1) Follow as stated above. Make the new folder called "usermaps".
2) Inside \Steam\steamapps\workshop\content, there is a folder for BO3, called "311210". Copy every subfolder from that folder into your new usermaps folder.
3) Each of those subfolders is either a mod or a map. Pick a folder that is 100% a map (mp_killhouse_z is a great example) and open the workshop.json file inside (use notepad++).
4) Inside that .json file is the folder name of the original file. Copy it. (in this case, it will be mp_killhouse_z). Use that copied name to rename the main folder numbered folder inside your usermaps folder that holds that map (so instead of ########## numbers, it should now be mp_killhouse_z). 
5) Inside mp_killhouse_z, make a "zone" folder. Throw all files into the new zone folder from that map except for the workshop.json file. You should now have the zone folder and the workshop.json file inside the mp_killhouse_z folder, nothing else.
6) This should now allow you to properly launch the map in custom games, using the usermaps default mod (loads automatically when you select a custom map). The custom map name in game will be the same as the folder name from the workshop.json (so instead of the English language: Killhouse Z, it will be mp_killhouse_z). 

With that, I would like to thank WantedDV for helping me out, and this issue will be closed as it is redundant to a point, and a new one will be opened for the devmap issue, as it is technically unrelated (sorry for the bad formatting, momo)
