### ISSUE TITLE
Hide Custom Maps button if no usermaps installed

### ISSUE THREAD

**Issue by WantedDV** [momo5502/boiii#415]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. launch MP
2.  goto map selection menu and click on custom maps

### Expected Result

Hide Custom maps button if there are no mp maps in `usermaps` or show a general preview image.

### Actual Result

![custommap](https://user-images.githubusercontent.com/122710241/228987856-5d2bccbd-5a0a-45df-9d8e-ffb5d90ef642.PNG)

### (Optional) Proof and Additional Information

This is not an issue if custom maps are installed.

![map2](https://user-images.githubusercontent.com/122710241/228987911-b89f5e92-1890-4eb9-8ac8-7820a8fb50b0.PNG)

### Severity/Priority

Minor

**Comment by momo5502** [comment]
pretty useless to spend time on this imo

**Comment by Brentdevent** [comment]
For me the button disappears, I can't replicate this. Got an empty usermaps folder in the root directory + steam is closed.
Anyway I agree with momo. 
![image](https://user-images.githubusercontent.com/70229620/229276911-b58961ea-6cde-4058-a707-049058e266b5.png)

**Comment by FragsAreUs** [comment]
this issue is related to people who dont own the game threw steam as bo3 is/was intented to use the steam workshop to download custom maps and what not. So imo it is also a usless thing to tackle because I am pretty sure if you did the same thing if you own it on steam it would display the same issue.

**Comment by mjkzy** [comment]
this should be marked as low priority and good first issue as it's cool for a beginner to tackle something like this :D
