### ISSUE TITLE
Adding Back in Black maps into the game's client

### ISSUE THREAD

**Issue by IronCrisp** [momo5502/boiii#419]
### Duplicate Issue Check

- [x] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

Since BOiii aims to be the definite Black Ops 3 experience for PC users, I want to suggest to include support for the PS4 exclusive "Back in Black" maps that PlayStation users used to get once they pre-ordered the PS4 version of Black Ops 4.

**Comment by momo5502** [comment]
#55
