### ISSUE TITLE
I cant add or see my steam friend in the menu or server browser

### ISSUE THREAD

**Issue by hahahaaaaaaaaa** [momo5502/boiii#421]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

me and my friend have the client running but when we don't have a way to add each other on the friends list, or even use steam to invite each other to a private match.

So the question is, is there a way to do that?

**Comment by Dss0** [comment]
Duplicate issue: https://github.com/momo5502/boiii/issues/175
There is no friends integration, right now you can only connect directly via ip.
