### ISSUE TITLE
cant figure out how to change my name

### ISSUE THREAD

**Issue by adamhernali** [momo5502/boiii#422]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

its just a name change 

### Expected Result

changing name

### Actual Result

nothing

### (Optional) Proof and Additional Information

ok

### Severity/Priority

High/Critical

**Comment by D3AL1O** [comment]
/name [insert name here] then restart the game.

**Comment by diamante0018** [comment]
Follow the advice you were given. Additionally this is possibly a duplicate of #406 .
I don't think you actually checked whenever a similar issue was already open when you opened this.

**Comment by RyhZM** [comment]
brother.... 😭
