### ISSUE TITLE
Unable to connect to private game

### ISSUE THREAD

**Issue by xMido95** [momo5502/boiii#423]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

Medium: The bug can be reproduced intermittently

### Steps to Reproduce

1.  Start a private game
2.  give your ip to your friends ? port maybe ?
3.  how do my friend can connect to my private game , Pls help we tried to do connect + ip (with and without port)

### Expected Result

Friends joining my private game

### Actual Result

nothing

### Severity/Priority

Medium

**Comment by momo5502** [comment]
such questions should be asked in the discord. connecting works, you are doing it wrong

**Comment by xMido95** [comment]
Where's the discord please could not find it (Im very bad at understanding how GitHub works)
