### ISSUE TITLE
Wheres the discord

### ISSUE THREAD

**Issue by Mxmentum** [momo5502/boiii#427]
### Duplicate Issue Check

- [ ] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

bro idk where the discord is

**Comment by momo5502** [comment]
oh jesus. it's available for sponsors. which you should be as you clearly did not compile it yourself.

but you aren't, as you certainly got it from a 3rd oarty source. 

dealing with issues like this and similar questions is what i've been doing for the past days. this slows down the devlopment immensly and it's kinda sad. the client is not released for a reason.

you guys should not be so impatient and cause me unnecessary work :(

the more questions like this people ask me, the longer the actual release will take
