### ISSUE TITLE
Black market and liquid divin

### ISSUE THREAD

**Issue by dravpin** [momo5502/boiii#429]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

Are there any plans to eventually implement Black market and liquid divinium? i know its technically useless because of the unlock all cheat but it would be fun to be able to properly level up and unlock the unlockables

**Comment by Dss0** [comment]
> ### Duplicate Issue Check
> 
>     * [x]  I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

.. https://github.com/momo5502/boiii/issues/292

It's an open issue so yes there are plans to get that to work eventually.
