### ISSUE TITLE
Feature (URGENT)

### ISSUE THREAD

**Issue by Divity** [momo5502/boiii#43]
Implement the proper rcon support and real time logging changes fed and Mikey implemented allowing iw4m admin to function fully on t7

https://github.com/mjkzy/t7-mod-1

**Comment by momo5502** [comment]
This is a very spamy issue. This is in no way urgent. There is definitely no need to rcon support at the moment. There is not even multiplayer support.

**Comment by mjkzy** [comment]
plus, if this ever does happen for boiii, i'm going to do clientside modifications to make this way better. t7-mod is only meant for dedicated use without a modified client.
