### ISSUE TITLE
use static loadscreen image for dedicated server

### ISSUE THREAD

**Issue by WantedDV** [momo5502/boiii#436]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

Intro cinematics should be exclusively for solo matches. Here is what I found in the lua that might help disable them in replace of static loading images:

- search `loading.lua` for `Engine.StartLoadingCinematic`. The function surrounding this has a few checks:
    - If chronicles map then break.
    ```lua
    if registerVal3 ~= "zm_asylum" and registerVal3 ~= "zm_cosmodrome" and registerVal3 ~= "zm_moon" and registerVal3 == "zm_sumpf" or registerVal3 == "zm_temple"
    ```
    - If more than one client in lobby then break.
    ```lua
  Engine.GetLobbyClientCount
  ```
   aside from splitscreen, this will always be 1 for boiii as we do not use lobbies. This could be the root of the problem.

### Additional info
- get the loading image for the selected map  with `CoD.GetMapValue(Engine.GetCurrentMap(), "loadingImage", "black")`
- there is a dvar `Engine.SetDvar("ui_useloadingmovie", 0)` but it seems to get overwritten upon loading.

**Comment by momo5502** [comment]
static loadscreens are a workaround from the devs because the client bugs out if the intro is played. we have a workaround for intros simply being skiped after loading. seems like the better alternative to me
