### ISSUE TITLE
I can't open the boIII

### ISSUE THREAD

**Issue by ItzLuke23** [momo5502/boiii#437]
### Duplicate Issue Check

- [ ] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

I downloaded today the client, but i can´t open it, i don´t know why. any solution?
![Screenshot_1](https://user-images.githubusercontent.com/129801514/229640311-d6aba52c-9744-4ea6-8ad9-9ce97fdf1bf0.png)

The window says: This application cannot be run on your computer. To find a version for your computer, check with the software publisher.

**Comment by pistakilla** [comment]
Where's you get the exe?

**Comment by ItzLuke23** [comment]
From merge pull request #434

**Comment by pistakilla** [comment]
Ask in the discord...you're in it right?

**Comment by ItzLuke23** [comment]
no, i'm not there

**Comment by pistakilla** [comment]
Figured...perhaps if you want to test boiii, I suggest you support Momo's work instead of opening an issue for just trying to get the game working which you're not sponsored to do so. Asking redundant questions like this slows the process to release the client.

**Comment by mjdeen** [comment]
> Ask in the discord...you're in it right?

what discord is it?

**Comment by FragsAreUs** [comment]
you can only have access to the discord if you have sponsored the project via patreon or github

**Comment by mjdeen** [comment]
> you can only have access to the discord if you have sponsored the project via patreon or github

ahh ok ty

**Comment by Blaeco** [comment]
any fixes?

**Comment by momo5502** [comment]
the client is not released.
only sponsors get access.

**Comment by josephpalabay12** [comment]
https://gyazo.com/7edd87492cf016824cee7c1dad244977

Says this as well.
