### ISSUE TITLE
Difficulty setting

### ISSUE THREAD

**Issue by WWWBBB001** [momo5502/boiii#438]
### Duplicate Issue Check

- [ ] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

This client is currently in good use. But there is a small suggestion. After setting the difficulty level each time, we need to set it again next time. Can you improve it. Of course, this is just a small issue, if possible

**Comment by diamante0018** [comment]
I don't know what this means, can you explain?

**Comment by WWWBBB001** [comment]
> I don't know what this means, can you explain?
BOT difficulty settings always reset，Can I save the previous settings？So I don't have to reset the BOT difficulty every time。

**Comment by vos6434** [comment]
I think they're talking about multiplayer bot difficulty.

**Comment by diamante0018** [comment]
Oh well you should make a GSC script to override the default behaviour then in my opinion. Boiii modifies the core of the game. We can override the game scripts but I don't think this is a good reason for us to do so. OP should learn how to GSC to achieve their goal.

**Comment by hxj662630** [comment]
i try to modify 'bot_difficulty' in  \Call of Duty Black Ops III\players\user\config.cfg ,but it didnt work

**Comment by diamante0018** [comment]
I recommend you lot check, the scripts from the mod tools. It could be apparent from there as to why the dvar is not working.
Perhaps you are assuming the dvar `bot_difficulty` actually exists?

**Comment by WWWBBB001** [comment]
谢谢各位，这只是个无关紧要的问题

**Comment by WWWBBB001** [comment]
Thank you, everyone. This is just an insignificant issue
