### ISSUE TITLE
Can chat support other languages

### ISSUE THREAD

**Issue by liveskai** [momo5502/boiii#446]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

# Can chat support other languages

**Comment by diamante0018** [comment]
Yes and no. If you are russian for example you will be able to type in the chat and chat with other russian players but English players will not be able to see your text in Cirillic and will see clobbered text.
Hope this answers your question but also you should not open issues for things that are neither bugs or feature requests. The client is under close testing.
