### ISSUE TITLE
Keep Current Camo when pack a punching

### ISSUE THREAD

**Issue by HeyItsJinx** [momo5502/boiii#453]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

If possible, when you pack a punch, keep whatever camo you put on your gun or make it a choice if you want to keep your camo or go with the camo's the map has built in.

**Comment by diamante0018** [comment]
Hello, we already have an issue opened for loading custom textures. Other then that this is a modding feat that is up to the user to achieve with mod tools.
