### ISSUE TITLE
`steam_proxy::get_player_name()` fails on Linux/Proton

### ISSUE THREAD

**Issue by MotoLegacy** [momo5502/boiii#458]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Linux, SteamOS

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. Launch `boiii.exe` via Proton
2. Look at Player name.

### Expected Result

`steam_proxy::get_player_name()` correctly grabs my Steam Profile name and uses that for my BOIII client name.

### Actual Result

Player name is what is returned by `utils::nt::get_user_name()` (Always `steamuser`)

### (Optional) Proof and Additional Information

![steamuser](https://user-images.githubusercontent.com/26030250/230641210-39b74561-c017-44cd-a7cc-6ea13535375a.png)

### Severity/Priority

Minor

**Comment by momo5502** [comment]
use the name command. the steam name is only taken as default name, so not worth fixing imo

**Comment by MotoLegacy** [comment]
Sure thing, will close as such.
