### ISSUE TITLE
Enable DLC Weapons

### ISSUE THREAD

**Issue by amrurikaj** [momo5502/boiii#46]
I think if you can enable DLC weapons or black market also is the good things.

![image](https://user-images.githubusercontent.com/113702897/194435842-17da900b-814e-45a2-acb2-45dd58443cd6.png)

**Comment by momo5502** [comment]
Will probably require bdMarketplace emulation

**Comment by joseupp** [comment]
At the moment with this mod you can have everything unlocked.
https://steamcommunity.com/sharedfiles/filedetails/?id=2818689863

**Comment by amrurikaj** [comment]
> At the moment with this mod you can have everything unlocked.
> 
> https://steamcommunity.com/sharedfiles/filedetails/?id=2818689863

nice 😎👍

**Comment by CrazyCSIW6** [comment]
When it comes to Black Market, I was able to get pending rewards but I can't claim them. Console doesn't seem to spit out anything interesting either.

**Comment by CrazyCSIW6** [comment]
![image](https://user-images.githubusercontent.com/51261276/200456238-c3de6fad-ee30-45b7-9409-03210dcdd2e3.png)
Some extra camos require COD Points to purchase, but you cannot gain COD Points in any way at the moment. Attempting to buy them throws an error at the processing screen.

**Comment by LevelChecker** [comment]
> ![image](https://user-images.githubusercontent.com/51261276/200456238-c3de6fad-ee30-45b7-9409-03210dcdd2e3.png)
> 
> Some extra camos require COD Points to purchase, but you cannot gain COD Points in any way at the moment. Attempting to buy them throws an error at the processing screen.

This project is in extremely early development this is to be expected

**Comment by CrazyCSIW6** [comment]
I never said it wasn't to be expected

**Comment by CrazyCSIW6** [comment]
this issue is still open???

**Comment by LevelChecker** [comment]
yes because other things are higher priority

**Comment by momo5502** [comment]
afaik this is done
