### ISSUE TITLE
Failed To Map BlackOps3.exe

### ISSUE THREAD

**Issue by RizonFTW** [momo5502/boiii#465]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. Open BOIII launcher
2. Press play

### Expected Result

Launching BackOps3

### Actual Result

Loads error "Failed To Map: BlackOps3.exe"

### (Optional) Proof and Additional Information

I have my BlackOps3 on a different drive along with the BOIII files and still get this error. I've tried verifying the files and reinstalling, but nothing is working.

### Severity/Priority

Medium

**Comment by SwordSWD** [comment]
You need to put boiii.exe in the black ops 3 installation folder. In the future for support please go to the discord. github issues are only for bug reports and feature requests

**Comment by AustinL3127** [comment]
same here. reinstalled BO3 then added the exe back into the BO3 files and i just get a black screen over and over

**Comment by momo5502** [comment]
> same here. reinstalled BO3 then added the exe back into the BO3 files and i just get a black screen over and over

This means you have broken game files. Try to verify them through steam or ask in the discord for help.

The main problem in this issue tho is that the boiii.exe needs to be in the BO3 folder
