### ISSUE TITLE
add playit.gg support to this

### ISSUE THREAD

**Issue by d524342423** [momo5502/boiii#466]
servers have a issue they all use port 27017 in bo3 but imagine giving support for playit.gg so we can host servers with any port not just 27017

**Comment by SwordSWD** [comment]
You can just use radmin...

**Comment by d524342423** [comment]
> You can just use radmin...

yeah but radmin isnt very good and you cant host it public for all to play where as using playit random people can join.

**Comment by FragsAreUs** [comment]
pls use the proper template when writing this

**Comment by d524342423** [comment]
> pls use the proper template when writing this. But also note you can use other ports other then 27017 when hosting servers if you check the server browser the servers there have different ports that was an issue that was fixed early on

sorry i am not really used to using github much ive not used in about 2 years also thanks yeah i saw a video on that i had no idea this added that because i didnt see anything about that being added thank you.

**Comment by diamante0018** [comment]
You can set net_port dvar and control the port.
To my understanding it's a non issue.
