### ISSUE TITLE
can yall make joining your friends easy like BO2 plutonium

### ISSUE THREAD

**Issue by darkerraven** [momo5502/boiii#467]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

my friends get spike ping on Radmin VPN, unlike bo2 plutonium easy to join faster and ping less

**Comment by MaDaAi** [comment]
honestly I don't know anything about code, but wouldn't this help security too. Having a sign in system and allowing to add players would be a win win. I could 100% be wrong.

**Comment by momo5502** [comment]
#175
