### ISSUE TITLE
boiiiimexe not trusted file?

### ISSUE THREAD

**Issue by Cracker941** [momo5502/boiii#468]
### Bug Type

Other

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. 
2. 
3. 

### Expected Result

open download

### Actual Result

wont open download and says not trusted file

### (Optional) Proof and Additional Information

x

### Severity/Priority

Medium

**Comment by momo5502** [comment]
allow it then, or mark it as trusted
