### ISSUE TITLE
everytime i start the game there is a issue 'Could not find zone 'en_core_pre_gfx' could someone help me please?

### ISSUE THREAD

**Issue by musabbbbb** [momo5502/boiii#474]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

no mods or anything just starting the game make problems

### Expected Result

i want to play the game

### Actual Result

it crashes 

### Severity/Priority

High/Critical

**Comment by momo5502** [comment]
your game files are broken, verify then through steam
