### ISSUE TITLE
"Failed to map boiii.exe" message keeps coming up when trying to start game

### ISSUE THREAD

**Issue by Jackvince01** [momo5502/boiii#475]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. 
2. 
3. 

### Expected Result

To be able to play game.

### Actual Result

Not starting due to message in the title.

### Severity/Priority

High/Critical

**Comment by momo5502** [comment]
you need to put the boiii exe in the bo3 game folder

**Comment by Jackvince01** [comment]
Hi there, Thanks for getting back to me, if I’m honest I am terrible with PCs I have only just bought this one recently. I can’t seem to find an actual bo3 folder, just a shortcut from steam. How do I find the folder? Sent from my iPhoneOn 9 Apr 2023, at 14:41, Maurice Heumann ***@***.***> wrote:﻿
you need to put the boiii exe in the bo3 game folder
