### ISSUE TITLE
Is it possible to make the host pause game while playing a private match in zombies with friends? like bo4 zombies

### ISSUE THREAD

**Issue by darkerraven** [momo5502/boiii#476]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

if that is possible that will be amazing feature!

**Comment by diamante0018** [comment]
No, it's not possible. Hope that answers your question.
It would probably require some massive modification of the engine if I had to take a guess.
I don't think it's worth developing time.

**Comment by Aziks0** [comment]
It might be possible to freeze zombies and players with GSC scripting, but you should ask this question on a BO3 modding forum/discord or whatever, as it's not really a boiii related feature.
