### ISSUE TITLE
Cant execute the launcher

### ISSUE THREAD

**Issue by Damire2000** [momo5502/boiii#479]
### Bug Type

Client, Other

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

I try to start the aplication but it appers a messaje telling me: Not possible to execute the aplication in this computer.
To search  a version for your computer, please check it with the software owner.
What i can do?
Thanks

### Expected Result

Can play with the launcher

### Actual Result

Cant even open the launcher

### (Optional) Proof and Additional Information

![image](https://user-images.githubusercontent.com/130305202/230790994-da45e15c-4ee3-49e0-8901-c115ea678cea.png)

### Severity/Priority

Medium

**Comment by zeker4321** [comment]
Is you're computer a 32-bit system? If so, you'll be unable to play the game on your PC.

**Comment by Damire2000** [comment]
> Is you're computer a 32-bit system? If so, you'll be unable to play the game on your PC.
No, its 64 bits and Windows 10 Pro, i have the game and i played it normal, but the launcher didnt work for me..

**Comment by momo5502** [comment]
Boiii is only available to sponsors for now
