### ISSUE TITLE
console doesn't seem to work

### ISSUE THREAD

**Issue by exodisium** [momo5502/boiii#484]
when trying to connect with console nothing happens, tried to use other console commands (disconnect, camerashake, etc...) all of which don't do anything. could be doing something wrong maybe?

**Comment by ImAciidz** [comment]
are you writing / in front of the commands you're trying to use

**Comment by momo5502** [comment]
either type / in front of your commands. \ also works. you can also just press tab before pressing enter.

**Comment by exodisium** [comment]
dude im stupid lol. sorry for wasting your time
