### ISSUE TITLE
ZM Dedicated Servers Crash On Latest Update

### ISSUE THREAD

**Issue by 0ptimusX** [momo5502/boiii#486]
### Bug Type

Dedicated Server

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Windows Server 2019

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. Start a dedicated zm server running any map
2. 
3. 

### Expected Result

Dedicated Server Runs without Issues.

### Actual Result

The Dedicated Server will crash after a short duration typically 10-20 mins.

### (Optional) Proof and Additional Information

[boiii-crash-2023-04-09-11-25-30.zip](https://github.com/momo5502/boiii/files/11189512/boiii-crash-2023-04-09-11-25-30.zip)
No issues before the latest update

### Severity/Priority

High/Critical

**Comment by momo5502** [comment]
70124977fb8feda6a3bb828a68710143a9558d4b (b707f65d61d2f1f3ba26e1ef4bf79b768de99f1f)
