### ISSUE TITLE
Server Browser LUI Error

### ISSUE THREAD

**Issue by ssnob** [momo5502/boiii#491]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. Launch the game
2. Select Multiplayer
3. Select Public Match
4. Click the Server Browser
5. Error.

### Expected Result

A list of available servers to join

### Actual Result

UI Error pops up, no servers show.

### (Optional) Proof and Additional Information

![image](https://user-images.githubusercontent.com/86132963/230962263-b61d9994-87ed-4606-b1bf-088e9cc194e9.png)
![image](https://user-images.githubusercontent.com/86132963/230962313-8beb1fa3-0608-4c84-b615-7f078b621f69.png)

### Severity/Priority

Minor

**Comment by JariKCoding** [comment]
Try redownloading the latest exe

**Comment by diamante0018** [comment]
Why don't you get help from the shady website you downloaded this from instead of bothering us?
Better yet, wait for this client to be released patiently?

**Comment by ssnob** [comment]
@diamante0018 Not sure where the hostility is coming from. The only website here is github, and this was built from the source. If you're going to cry people using it why continue to leave this repo public? @JariKCoding yes latest build fixes thanks!
