### ISSUE TITLE
Critical Error when opening server browser or when trying to connect directly with IP address

### ISSUE THREAD

**Issue by exodisium** [momo5502/boiii#495]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. Open server browser
2. OR open console, use /connect command and try to connect

### Expected Result

Connect to server

### Actual Result

Fatal error (0xC0000005) at 0x00000223022E9894 (0x00000001422E9894). 
A minidump has been written. 

### (Optional) Proof and Additional Information

![crash](https://user-images.githubusercontent.com/130352108/231013462-d5e8bc95-e1c0-40a0-8141-bad89f7738c0.PNG)
[boiii-crash-2023-04-10-18-46-58.zip](https://github.com/momo5502/boiii/files/11194580/boiii-crash-2023-04-10-18-46-58.zip)

### Severity/Priority

Medium

**Comment by diamante0018** [comment]
Custom exe from unknown origin are not supported. Try again with the latest exe.

**Comment by exodisium** [comment]
Is it possible to get latest executable without having it on steam?

**Comment by momo5502** [comment]
yes, if you become a sponsor
