### ISSUE TITLE
map_rotate compatibility with config and startup bat for ZM Servers

### ISSUE THREAD

**Issue by SwordSWD** [momo5502/boiii#499]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

If you put map_rotate in the server_zm.cfg or in the startup bat, It will crash. The work around is you have to manually map rotate after every restart, Would be nice if this was supported for zombie servers.

**Comment by Dss0** [comment]
what do you mean by "you have to manually map rotate after every restart"? The server starts the map rotation when you start it, the lua scripts that also sets the game mode to zombies is responsible for that. That's also why it has been removed from the startup script.

**Comment by SwordSWD** [comment]
> what do you mean by "you have to manually map rotate after every restart"? The server begins the map rotation when you start it, the lua script that also sets the game mode to zombies is responsible for that. That's also why it has been removed from the startup script.

It doesn't for me. Everytime when i boot up the server It says **Server not running** i have to manually enter `map_rotate` just for the server to turn on. I have to do it every restart

**Comment by Dss0** [comment]
do you have the latest server configs from my repo with `set sv_skip_lobby "1" ` set?
This can be closed btw, not a client issue.

**Comment by diamante0018** [comment]
> do you have the latest server configs from my repo with `set sv_skip_lobby "1" ` set? This can be closed btw, not a client issue.

Roger
