### ISSUE TITLE
cant enter the game

### ISSUE THREAD

**Issue by MarcoFragola** [momo5502/boiii#514]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. open boiii client
2. starts runing then closes
3. 

### Expected Result

it should open as normal and let me play 

### Actual Result

it closes at the moment when i open the server

### Severity/Priority

High/Critical

**Comment by momo5502** [comment]
can you try verifying your game files? feels like broken files.

**Comment by MarcoFragola** [comment]
> can you try verifying your game files? feels like broken files.

yeah tried almost everything and poeple in discord where suggesting but yet didnt work any of them

**Comment by MarcoFragola** [comment]
https://user-images.githubusercontent.com/120483050/231828973-5742f6aa-54ce-431a-8699-91c3eb8a3040.MOV

**Comment by momo5502** [comment]
this looks like the protection from the game kicking in. the game exits like that if "cheat tools" are open.
some of the tools, like ida or hxd are patched and work, but others don't, for example cheat engine or so.
do you have any tools installed/open that could be considered cheat or reverse engineering tools?

if so try to remove/close these

**Comment by MarcoFragola** [comment]
i have none. It could be my anti virus that is detecting a malicious file but I have already excluded it from blocking
