### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Nikznkk** [momo5502/boiii#515]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

![image](https://user-images.githubusercontent.com/130590898/231528846-efddd59d-1706-498e-8689-7f1b75f81d7c.png)

how do i solve this problem?
and be able to play online with my friends?

**Comment by momo5502** [comment]
the client is only available to sponsors for now. you can sponsor here: https://linktr.ee/momo5502

**Comment by Nikznkk** [comment]
Hey, so how can i play via LAN?

**Comment by Nikznkk** [comment]
Because for example, when I try to use /connect and my friend's IP, the screen goes black and does not load.

**Comment by momo5502** [comment]
you cant, you don't have the client. what you showed in your screenshot is a super outdated version.

that shows you are not a sponsor.
you need to donate and get the latest files

**Comment by Nikznkk** [comment]
oh ok momo, Thanks for the help!
