### ISSUE TITLE
Cant start the client

### ISSUE THREAD

**Issue by michaelbash** [momo5502/boiii#518]
Asks for an active internet connection which I do have and firewall is not blocking it

![image](https://user-images.githubusercontent.com/43926910/231561674-4485b6a8-b0ed-4320-a63f-128a3ec8c183.png)

**Comment by MarcoFragola** [comment]
u need to have bo3 installed, via steam or free on torrent

**Comment by michaelbash** [comment]
it is installed and the client is in the game folder. steam version

**Comment by pistakilla** [comment]
Ask in the discord for support.

**Comment by momo5502** [comment]
redownload the exe from the discord. i fixed this yesterday, but the error comes from the updater, so auto updating wont work 😂
