### ISSUE TITLE
boiii wont let open

### ISSUE THREAD

**Issue by josephpalabay12** [momo5502/boiii#520]
### Bug Type

Other

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit)

### Reproducibility Rate

Medium: The bug can be reproduced intermittently

### Steps to Reproduce

1. n/a
2. n/a
3. n/a

### Expected Result

This app cant run on your pc

### Actual Result

exe wont open

### (Optional) Proof and Additional Information

https://gyazo.com/7edd87492cf016824cee7c1dad244977
![7edd87492cf016824cee7c1dad244977](https://user-images.githubusercontent.com/57514900/231608119-7032e42d-2d65-47d9-95cf-4fdf744410ba.png)

Running windows 11 home
disabled av and realtime protection

### Severity/Priority

High/Critical

**Comment by FaridTarakai** [comment]
Hi, I had this kind of problem with another game called black ops 1
either the BOIII client isnt compatible or the actual game isnt.
if your game is cracked, then right click the .exe then select properties. the go to compatibility. tick the box to run this app for compatiblity for then choose one of of the operating systems. like windows 8.1
if u brought it on steam then the BOIII client could be the problem and just follow these steps for the BOIII client

**Comment by FaridTarakai** [comment]
again im not very sure about this
but it could work

**Comment by momo5502** [comment]
the client is only available to sponsors for now
