### ISSUE TITLE
Show reason for getting kicked from server.

### ISSUE THREAD

**Issue by efinst0rm** [momo5502/boiii#523]
### Bug Type

Client, Dedicated Server

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Windows Server 2019

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

When a user gets kicked from the server currently they're only shown a generic kick message " Server Disconnected - player has been kicked."
![image](https://user-images.githubusercontent.com/7751074/231629308-5e761f72-655c-4d76-87f3-aad832bd1dc6.png)

### Expected Result

Should show the actual reason why player was kicked for example "Server Disconnected -  VPNs are not allowed on this server. For more information, go to https://namelessnoobs.com/"

### Actual Result

Does not tell/show the client why they were kicked from the server.

### Severity/Priority

Minor

**Comment by diamante0018** [comment]
Use clientkick_for_reason command

**Comment by diamante0018** [comment]
![image](https://user-images.githubusercontent.com/37080671/231711760-38242ea4-01a6-4d9a-8b0c-784b3531ce68.png)
Made a pr to IW4M as well

**Comment by diamante0018** [comment]
I made a pr to IW4M as well!
