### ISSUE TITLE
BOIII Crash Dump

### ISSUE THREAD

**Issue by liveskai** [momo5502/boiii#53]
[boiii-crash-2022-10-09-16-00-25.zip](https://github.com/momo5502/boiii/files/9741047/boiii-crash-2022-10-09-16-00-25.zip)
[boiii-crash-2022-10-09-16-02-34.zip](https://github.com/momo5502/boiii/files/9741048/boiii-crash-2022-10-09-16-02-34.zip)

**Comment by momo5502** [comment]
Crash is in BG_StringHashValue within BG_InitWeaponString

**Comment by momo5502** [comment]
My initial assumption would be bad game files

**Comment by momo5502** [comment]
Closing this as it's for the old binary and thus useless
