### ISSUE TITLE
Also please late me change the rate 

### ISSUE THREAD

**Issue by chase447** [momo5502/boiii#532]
### Duplicate Issue Check

- [ ] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

Via /rate in console

**Comment by Brentdevent** [comment]
If you open feature request, please give us a clear description of the feature you requesting. 
What rate you want to change?

**Comment by diamante0018** [comment]
No reason to bother with such incomplete tickets. Only 4 words.
