### ISSUE TITLE
ZM Origins - Assets not loading in properly and LOD Detail is aggressively culling.

### ISSUE THREAD

**Issue by HeyPortal** [momo5502/boiii#533]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. Launch Origins in a private game.
2. LOD is most aggressive in No Man's Land but is somewhat apparent in spawn room and trenches.
3. Under Pack-A-Punch the crypts are missing textures.
4. You can force the assets to load from a distance if you aim down sights. 

### Expected Result

Assets should be loaded within view of the player without the need to be immediately in front of it. Textures should be included in the crypts as seen below in the before and after clips.

### Actual Result

https://1drv.ms/f/s!Ah57PD7koROAnE734ygTsrdH1Nnq?e=IU84H7

The clips attached demonstrate the issues. 

### Severity/Priority

Medium

**Comment by Brentdevent** [comment]
This seems like a map issue because this is also present on the steam version, however you can change the dvar `r_lodbiasrigid`. 
Type `/r_lodbiasrigid -1000` in the console. That will solve your issue
