### ISSUE TITLE
network

### ISSUE THREAD

**Issue by TimoTe0** [momo5502/boiii#538]
### Bug Type

Dedicated Server

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/130423932/232124524-0ee75a6c-785f-4cb7-9288-ff0177c44b90.png)

im from argentina and i had been wating for a brazilian or argentinian sv to play with less ms
these days i saw this sv from br and i dont understand why i have 180ms
usually i play in br with almost 60ms idk if this is a bug or an internet problem

### Expected Result

to fix this ms problem :(

### Actual Result

it doesnt fix XD

### Severity/Priority

Medium

**Comment by efinst0rm** [comment]
This is not a bug. BOIII does not host any servers, All the server you see are hosted by the testers.
