### ISSUE TITLE
Unlock all Supply Drop loot only

### ISSUE THREAD

**Issue by Jayblu360360** [momo5502/boiii#539]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

I really think there should be a feature in the stats section where you can enable or disable “unlock all supply drop loot” because for the people who want to level up and unlock loot how it was intended but not have to pay for supply drop loot I think this would be good. I know you can unlock it with the all loot stat but I think there should be one specifically for the supply drop weapons  .

**Comment by darkerraven** [comment]
I agree! I want this feature (:
