### ISSUE TITLE
getinfo: add current zm round

### ISSUE THREAD

**Issue by mxve** [momo5502/boiii#541]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

Title pretty much says it all, would be nice to get the current zombie mode round in the getinfoResponse.
I'd personally use this for my server list (https://list.plutools.pw/boiii), but this may also be something useful to add to the ingame server browser.

**Comment by diamante0018** [comment]
Removing the good first issue label because this is not trivial.
