### ISSUE TITLE
Can't connect to any servers

### ISSUE THREAD

**Issue by Fireew** [momo5502/boiii#544]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. Click the BOIII.exe
2. Then press Server Browser 
3. 

### Expected Result

I should see all the servers

### Actual Result

I can play solo I just can't play on servers.

### (Optional) Proof and Additional Information

![Desktop Screenshot 2023 04 14 - 22 38 59 25](https://user-images.githubusercontent.com/130717485/232304107-7e20fe79-aadc-4fd4-a8ad-68c2c0a6b29a.png)

### Severity/Priority

High/Critical

**Comment by momo5502** [comment]
The client is only available to sponsors right now. Feel free to sponsor here and get access to the project: https://linktr.ee/momo5502

**Comment by Fireew** [comment]
Alright

**Comment by Spidermanagent** [comment]
just fantastic!
