### ISSUE TITLE
CPU scheduling/optimization

### ISSUE THREAD

**Issue by Spidermanagent** [momo5502/boiii#545]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

So I notice that CPU scheduling in BO3 could be better optimized by tweaking some settings in the game file, but I haven't found any combination of settings that yields a "sweet spot" for smoother frame generation. The following strings in the config.ini can be tweaked:

//Number of frames the driver is allowed to enqueue, a lower value improves input latency but may decrease performance. Set it to 0 to use the system default, usually 3.
MaxFrameLatency = "3" // 0 to 4

//0 use two threads, one thread update frame N while the second render N-1. 1 concatenate update and render. 2 concatenate update render and frame presentation.
//0 is the default for the best performance, 1 and 2 improve latency but require a powerful CPU.
SerializeRender = "2" // 0 to 2

Additionally, I found some strings in BO4 config files that's missing from BO3 ini, but could potentially benefit the optimization:

///////////////////////////////////////////////////////////////////////////////////////////////////
// SYSTEM SETTINGS
//
// Notes:
// These settings are specific to this system's hardware, and are only applied at boot time.
///////////////////////////////////////////////////////////////////////////////////////////////////

//Thread count for handling the job queue
worker_threads = "14" // 2 to 16

I have not yet fully tested these strings & see how they affect in-game performance, but I hope that someone can do some testings to figure out which settings yield the best result.

**Comment by diamante0018** [comment]
Thanks you for letting us know.
We might add this info to some for of guide for the client.
