### ISSUE TITLE
Join server error

### ISSUE THREAD

**Issue by liveskai** [momo5502/boiii#548]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/54350655/232358870-6e01729f-c4cb-47f1-b2be-9ede8af6928b.png)

### Expected Result

![image](https://user-images.githubusercontent.com/54350655/232358928-899fc471-59de-4467-a3c7-580cbbfa7420.png)

### Actual Result

![image](https://user-images.githubusercontent.com/54350655/232358898-4a085ad5-bcaa-498d-b5d0-ef46483d1d92.png)

### Severity/Priority

High/Critical

**Comment by Brentdevent** [comment]
How did you setup the server? 
Did you use the server configuration from the AEE discord?

This error message shows up when the client has loaded a different mod than the server has.
So perhaps your server failed to load the mod?

More info is needed when making a bug reports.

**Comment by liveskai** [comment]
> This could be due to using an old version of the mod. "All Around Enhancement" shows the version on the top left near the join button. It is covered over in this photo but I think I can make out Something that looks like "Beta". Either you need to update your mod, or the server needs to downgrade.
> 
> The function that checks if mods are installed also checks the version of the mod with `ugcInfo.ugcVersion`. I do not know where this version information comes from though. Hope this helps...
> 
> ```lua
> f0_local0.Mods_Lists_IsInstalled = function ( f58_arg0 )
> 	return f0_local0.Mods_IsUGC( f58_arg0 ) and Engine.Mods_Lists_IsInstalled( f58_arg0.ugcType, f58_arg0.ugcName, f58_arg0.ugcVersion )
> end
> ```
The same version is used on both the client and server side
Latest 4.17

**Comment by Brentdevent** [comment]
Hmm, seems the mod get's loaded correctly. 
Have you tried joining someone else his server running the same mod?

Try to join this server and see if you get the same result.
![image](https://user-images.githubusercontent.com/70229620/232623269-d938f137-a6fa-4921-a340-f4a81b9d0543.png)

**Comment by liveskai** [comment]
> Hmm, seems the mod get's loaded correctly. Have you tried joining someone else his server running the same mod?
> 
> Try to join this server and see if you get the same result. ![image](https://user-images.githubusercontent.com/70229620/232623269-d938f137-a6fa-4921-a340-f4a81b9d0543.png)

Can join

**Comment by diamante0018** [comment]
So this is a modding related error, I don't think this is anything we can chase right now.
