### ISSUE TITLE
Boii.exe - bad image

### ISSUE THREAD

**Issue by Extee1** [momo5502/boiii#552]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

Low: The bug has only occurred once or a small number of times

### Steps to Reproduce

I moved the boii.exe into the bo3 folder and when I click on the application, then click play, it immediately brings me to an error called boii.exe - bad image and then proceeds to say “The game is not designed to run on windows or contains an error”

### Expected Result

I want to be able to launch boiii

### Actual Result

Game just crashes

### Severity/Priority

High/Critical

**Comment by Brentdevent** [comment]
The client is only available to sponsors right now. Feel free to sponsor here and get access to the project: https://linktr.ee/momo5502
