### ISSUE TITLE
BOIII 

### ISSUE THREAD

**Issue by jorgeblackmesa1995** [momo5502/boiii#556]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

Low: The bug has only occurred once or a small number of times

### Steps to Reproduce

Hola a todos 
cuando ejecuto el boiii.exe [Release Binary](https://github.com/momo5502/boiii/suites/12309774605/artifacts/652609254)
me sale el error 
" no se puede ejecutar esta aplicación en tu equipo"

alguna solución?

### Expected Result

pense que funcionaria y que era gratis para todos....

### Actual Result

pero me salta este error que mencione.
si alguien sabe el porque, le agradecería. 

### (Optional) Proof and Additional Information

.

### Severity/Priority

Minor

**Comment by pistakilla** [comment]
Boiii testing is available for sponsors only.

**Comment by Brentdevent** [comment]
Like pistakilla said the client is only available to sponsors right now. Feel free to sponsor here and get access to the project: https://linktr.ee/momo5502
