### ISSUE TITLE
Inability to join friends using any method

### ISSUE THREAD

**Issue by dinglechalk2** [momo5502/boiii#559]
### Bug Type

Other

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. Set up ip (either port forward or vpn)
2. Try to connect

### Expected Result

Should just join your friend

### Actual Result

Get a lot of errors and get an text box that says “ Script file not found: 'scripts/zm/core_frontend.gsc'” and freezes 

### (Optional) Proof and Additional Information

I put the priority as minor since it only seems to be my friend having this problem 

### Severity/Priority

Minor

**Comment by momo5502** [comment]
You have broken game files.

**Comment by dinglechalk2** [comment]
It still does not work

**Comment by dinglechalk2** [comment]
> You have broken game files.
> Verify your game through steam.

It still does not work

**Comment by pistakilla** [comment]
You should ask in the discord for support.
