### ISSUE TITLE
Minidump error when having any Custom Maps in usermaps folder

### ISSUE THREAD

**Issue by Grumblecorn2** [momo5502/boiii#561]
### Bug Type

Dedicated Server

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1.  Launch the server with maps in the usermods folder. Tested this with the maps Quiet Cosmos and Der Riese: Declassified
2.  Server will launch and have a lobby open with 0/4 players.
3.  Join and will crash the server within a few seconds while loading. This will apply to any base map as well as long as the Custom Maps Zone files are in the usermaps folder.

### Expected Result

Server will run and will be joinable.

### Actual Result

Server will very quickly crash upon joining

### (Optional) Proof and Additional Information

[boiii-crash-2023-04-19-02-24-50.zip](https://github.com/momo5502/boiii/files/11269462/boiii-crash-2023-04-19-02-24-50.zip)

Every crash dump I have involving this is identical to this one.

### Severity/Priority

High/Critical

**Comment by JustNato** [comment]
Please check the #Help-Server channel pins on how to setup user maps, I have seen people host these maps before just fine without any crashing.

**Comment by Grumblecorn2** [comment]
> Please check the #Help-Server channel pins on how to setup user maps, I have seen people host these maps before just fine without any crashing.

I have my server setup as the channel pins have suggested and gotten no response from the channel as to why the issue is going on, I have also seen people run these maps so I am genuinely confused

![image](https://user-images.githubusercontent.com/119527447/232992692-b54f3d12-cab9-4a45-ac29-8564f05f0c39.png)

![image](https://user-images.githubusercontent.com/119527447/232992965-4572e588-c28c-4f0c-a36d-3a8846127fa7.png)

This is setup correctly, right?

**Comment by Grumblecorn2** [comment]
.

**Comment by Grumblecorn2** [comment]
Gonna close this. Verified all my files and put all my files where they should be, despite after three days and doing this a few times prior, my files decide to work now. Apologies.
