### ISSUE TITLE
Steam must be running to start the game

### ISSUE THREAD

**Issue by BlackHeart797** [momo5502/boiii#563]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. Download t7_full_game
2. Launch boiii client
3. Click play and it says steam must be running

### Expected Result

Downloaded the provided torrent t7_full_game. The game must run without showing any error. I have the latest version of the client.

### Actual Result

I start the client and click play. It loads for sometime and says that steam must be running to play the game. I downloaded the torrent that you guys provided t7_full_game. And also launching boiii with steam didn't work. I have the latest version of boiii btw
![image](https://user-images.githubusercontent.com/131293197/233156149-dbd44782-43d6-4faf-9f01-75c71369588b.png)

### Severity/Priority

High/Critical

**Comment by JustNato** [comment]
Are you opening the client via boiii.exe?

**Comment by BlackHeart797** [comment]
> 

Yes

**Comment by JustNato** [comment]
What is your folder path that you installed the game in

**Comment by BlackHeart797** [comment]
![image](https://user-images.githubusercontent.com/131293197/233158287-178f6211-3a7c-4bb9-97c6-97c0d3dbcc88.png)

**Comment by diamante0018** [comment]
It's clear as day you are not using an official build of the client.
Right now it's only available to sponsors as we are still in close testing phase.
https://boiii.re/

**Comment by BlackHeart797** [comment]
I used the public version on github which is official
