### ISSUE TITLE
When I close the client after 10 minutes when I come back all the saves are deleted 

### ISSUE THREAD

**Issue by HAWAKEEN** [momo5502/boiii#569]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

when I close the client after 10 minutes when I come back all the saves are deleted, I have re-downloaded the game more than once and the problem still persists

### Expected Result

obviously maintain the client saves regularly 

### Actual Result

It doesn't crush nothing of this just after quiting the client/game, after 10 minutes when i re-open the client the progress are gone just like i installed for the first time the client, if i can I will show you the problem with a recording

### Severity/Priority

High/Critical

**Comment by pistakilla** [comment]
If you're talking about stats and how they don't save, you need to make sure you play all the way through the match until the match ends. The command `/uploadstats` may or may not work, but it's supposed to upload your stats to the stats files (I could be wrong though).

**Comment by HAWAKEEN** [comment]
> If you're talking about stats and how they don't save, you need to make sure you play all the way through the match until the match ends. The command `/uploadstats` may or may not work, but it's supposed to upload your stats to the stats files (I could be wrong though).
> 
> Also don't alt-f4 every match you play before the match ends, this may prevent any progress being saved.

Hi, your method doesn't work either, when I exit the game everything resets.
