### ISSUE TITLE
Sent back to menu and shown an error message whenever I try to load any zombies map, multiplayer servers and content work just fine.

### ISSUE THREAD

**Issue by Oreo5757** [momo5502/boiii#570]
### Bug Type

Other

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. 
2. 
3. 

### Expected Result

Should be able to load all maps and zombies content

### Actual Result

Every time I load a map it'll show me the blue forest and then itll show the map loading screen for a few seconds and give me the errors.

### (Optional) Proof and Additional Information

<img width="1109" alt="Screenshot 2023-04-20 083750" src="https://user-images.githubusercontent.com/131368600/233374094-c0ab35d4-55fb-4710-a31a-19202314b50c.png">
<img width="1183" alt="Screenshot 2023-04-20 083712" src="https://user-images.githubusercontent.com/131368600/233374148-fae308ac-0018-4dc0-8f8c-1e6e586a9296.png">
<img width="1188" alt="Screenshot 2023-04-19 205312" src="https://user-images.githubusercontent.com/131368600/233374158-b241110f-8ecb-4ae0-ade4-a8ddc8d292e9.png">
<img width="1886" alt="Screenshot 2023-04-19 185129" src="https://user-images.githubusercontent.com/131368600/233374225-fb66523c-5919-449a-96ef-7c3ec2888659.png">

### Severity/Priority

High/Critical

**Comment by diamante0018** [comment]
Sounds like an issue with your mod possibly

**Comment by Oreo5757** [comment]
idk what to do, I've uninstalled the game and deleted all the mods and put them back and its still the same.

**Comment by FragsAreUs** [comment]
also make sure you dont have /developer set to 2

**Comment by Oreo5757** [comment]
im pretty sure thats the issue, how do i undo that?

**Comment by diamante0018** [comment]
Not an issue with out client I can tell that much.
