### ISSUE TITLE
Some servers not showing and unable to /connect to them

### ISSUE THREAD

**Issue by sleepyacid** [momo5502/boiii#571]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit)

### Reproducibility Rate

Medium: The bug can be reproduced intermittently

### Steps to Reproduce

1.  Check External list for populated server (in this case Nameless Noobs) ![pic](https://cdn.discordapp.com/attachments/1073741856992669738/1098780679405326346/image.png) 
3.  Copy Ip & paste into console ![pic](https://cdn.discordapp.com/attachments/1073741856992669738/1098780679036223680/image.png)
4.  Nothing happens

### Expected Result

I can see the populated server and double click to connect / or  slash connect actually works and connects me to the server. 

### Actual Result

absolutely nothing + not enjoying life

it keeps me on the menu screen and the console does not update.

### (Optional) Proof and Additional Information

![Screenshot 2023-04-20 220748](https://user-images.githubusercontent.com/40345297/233524467-9ed6fb22-90fc-4b2e-8449-b3df42e7e9fa.png)
![Screenshot 2023-04-20 220900](https://user-images.githubusercontent.com/40345297/233524470-b5897df9-96bf-45e0-8838-0d001e01ec23.png)
![Screenshot 2023-04-20 221050](https://user-images.githubusercontent.com/40345297/233524474-77c8fbb9-3a18-462e-a215-76bead61448a.png)

all at the same time, trying to connect

### Severity/Priority

Medium

**Comment by momo5502** [comment]
The servers showing up in our ingame server list are the ones you should be able to connect to.
That is the only ever single source of truth.

**Comment by sleepyacid** [comment]
So NN just doesnt exist, got it. lol Also this doesnt explain /connect not working
