### ISSUE TITLE
can't play online on boiii

### ISSUE THREAD

**Issue by NaderBhm** [momo5502/boiii#573]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1-open game
2- try to go online

### Expected Result

opening the game and joining a server

### Actual Result

can't join server because client can't go online

### (Optional) Proof and Additional Information

![image](https://user-images.githubusercontent.com/131452520/233619158-0507cece-bb58-4a49-92de-715593740d1d.png)

### Severity/Priority

High/Critical

**Comment by pistakilla** [comment]
That looks outdated. Sponsor the project to get access to latest boiii version.

**Comment by momo5502** [comment]
boiii is only available to sponsors: https://linktr.ee/momo5502
