### ISSUE TITLE
Suggestion about discord Presence for low end PC

### ISSUE THREAD

**Issue by Stormiswe1** [momo5502/boiii#574]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

Hi so i'm not sure if you will take in count this request, due to the lack of people in the same case as me. I understand that doing somthing for maybe 100 people / 6000 is not a deal

I have an i5 6400 bottenlenck by my GTX 680, due to the lack of performance having any kind of program opened in the background will cause in heavier one such as discord or chrome, stutter issue and more input lag with less performance 
So to make sure to get the most performance out of my CPU i had to get in big optimisation such as windows and even debloat discord but i still get these performance issues so this is my point

- **Instead of having discord in the background while playing I propose a dayly verification or only having to run discord on boot then let us closing discord** 

Thanks

**Comment by diamante0018** [comment]
We will take these decisions internally and we we will take the necessary considerations. We do not need input about this from the community at this time
