### ISSUE TITLE
Steam hours tracking then getting reset after I close the steam app

### ISSUE THREAD

**Issue by Jxmbie** [momo5502/boiii#578]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1.  Open client with steam open 
2. Play client, any map or mode
3. Close client and check steam hours 
4. It will track but after closing and reopening steam it will go back to the previous hours before the most recent session

### Expected Result

The desired outcome should be that steam hours should be tracked

### Actual Result

Hours track then reset back to the previous hours before the session

### Severity/Priority

Minor

**Comment by diamante0018** [comment]
Works completely fine here.

**Comment by diamante0018** [comment]
Can't repro
