### ISSUE TITLE
BOiii says im not in the discord

### ISSUE THREAD

**Issue by ayeMerks** [momo5502/boiii#579]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1.  Launch BOiii client
2. It doesn't launch

### Expected Result

Launch BOiii client to play the game

### Actual Result

Says I need to have discord open to play the game, when I have discord fully updated and running, with the patreon server on it.

### Severity/Priority

High/Critical

**Comment by diamante0018** [comment]
See #576
