### ISSUE TITLE
No Audio

### ISSUE THREAD

**Issue by ywehbe7** [momo5502/boiii#582]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. When i load up the game, i have no audio from the beginning. 

### Expected Result

Expect to hear the game audio,

### Actual Result

No audio what so ever is heard.

### (Optional) Proof and Additional Information

1. Checked all windows and sounds setting properties they are all correct.
2. All in game settings are correct.
3. this is the only app this is happing in all my other games work fine.
4. have downloaded a fresh copy of BO3 from steam yet the issue persists.
5. and new version of BOIII client with no change to situation. 

### Severity/Priority

High/Critical

**Comment by diamante0018** [comment]
can't repro

**Comment by ywehbe7** [comment]
Is there any reason that i would not get audio from the boiii.exe while all my other apps work no problem?

**Comment by diamante0018** [comment]
Check audio settings and make sure your output devices is correct. it would be easier to help you on our discord

**Comment by ywehbe7** [comment]
ive done all that, and ive tried to reach out in discord to no response. my username is Parzival#9584. please help
