### ISSUE TITLE
Game crashes when refreshing server browser/accessing it

### ISSUE THREAD

**Issue by FrancescoCode1** [momo5502/boiii#583]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. Start the game
2. Open the server browser

### Expected Result

List the servers in the server browser

### Actual Result

crashes before showing the server browser

### (Optional) Proof and Additional Information

Seems im not the only one with the issue. Other users have also reported this behaviour

### Severity/Priority

High/Critical

**Comment by ImSlumpp** [comment]
+1
Server browser leads to CTD on both Multiplayer & Zombies
