### ISSUE TITLE
Fatal Error when I click the windows key

### ISSUE THREAD

**Issue by slxzt** [momo5502/boiii#588]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. Open Client and game normally
2. Load into a solo zombies game
3. Once in said game clicking the Windows key

### Expected Result

Results in a fatal error and a minidump

### Actual Result

Results in a fatal error and a minidump

### Severity/Priority

High/Critical

**Comment by diamante0018** [comment]
Without a minidump there is not much we can do

**Comment by diamante0018** [comment]
By the way, I can't repro.

**Comment by diamante0018** [comment]
No minidumps submitted
