### ISSUE TITLE
Steam playtime resets upon 2nd launch of game

### ISSUE THREAD

**Issue by lf5707** [momo5502/boiii#589]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. Open boiii, play for enough that steam playtime gets higher
2. Quit game
3. Relaunch boiii and your playtime will be reset to its original number before playing the first time

### Expected Result

Playtime should stay at the number it’s set as before relaunching the 2nd time

### Actual Result

Number of playtime reverts to original playtime before launching for the first time

### (Optional) Proof and Additional Information

https://drive.google.com/file/d/1wt0fQ1Pdc4RqIQmDnxoo3mtBVvbgjVh0/view?usp=share_link

### Severity/Priority

Medium

**Comment by momo5502** [comment]
@diamante0018 i thought we checked that this was fixed? I know you had an idea. But honestly I don't really care about that, or what do you think? Our goal is not to provide a proper steam integration. If anything, we want to get rid of steam.

**Comment by diamante0018** [comment]
I suggest to close as wontfix @momo5502

**Comment by diamante0018** [comment]
Not planned. Unless one of use changes their mind and can repro.
