### ISSUE TITLE
zm_common does not exist 

### ISSUE THREAD

**Issue by SaphirO46** [momo5502/boiii#593]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. go on multiplayer  
2. join any dlc zombie map in server research
3. 

### Expected Result

join the game

### Actual Result

fatal error : zm_common file is not found
![image](https://user-images.githubusercontent.com/116603599/234136584-8a789291-dec2-43f7-ab44-86f59a4a6f43.png)
for shadow of evil it's another error that tells me that some files of the map shadows of evils are missing

### (Optional) Proof and Additional Information

I bought only the multiplayer version for 15 euro 
![Capture d’écran 2023-04-25 011547](https://user-images.githubusercontent.com/116603599/234137099-1c83074f-3d92-47ad-8614-335371d2f143.png)
![Capture d’écran 2023-04-25 011526](https://user-images.githubusercontent.com/116603599/234137101-bc8f92a4-1943-463f-9b4b-9f0e99debf94.png)
trying to find the file zm_common in my bo3 folders I did not find it even though I downloaded t7_dlc.

I think it's because I only have the multiplayer and dlc files but not the basic zombie files.

ps : 
if so I should have put this report in the features to have a torrent of the missing files but I can't test I don't have enough space to download a second full version of bo3.

### Severity/Priority

Medium

**Comment by FragsAreUs** [comment]
the starter edition is only the multiplayer hence the name mutiplayer starter pack. so there for does not contain any zm files

**Comment by Brentdevent** [comment]
This is not an issue with BOIII you simply miss some files like FragsAreUs said, feel free to ask for support in the discord.
