### ISSUE TITLE
Open and report an error

### ISSUE THREAD

**Issue by WWWBBB001** [momo5502/boiii#597]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. 
2. 
3. 

### Expected Result

I played well yesterday, but I reported an error today

### Actual Result

I played well yesterday, but I reported an error today

### (Optional) Proof and Additional Information

![111](https://user-images.githubusercontent.com/62052061/234313491-ece8719d-97b7-46bd-9f60-b1f50a06773f.png)

### Severity/Priority

High/Critical

**Comment by WWWBBB001** [comment]
I haven't changed anything

**Comment by diamante0018** [comment]
Ask for help in our discord server for this issue.
Thanks
