### ISSUE TITLE
Black Screen when i start the game through "boiii.exe"

### ISSUE THREAD

**Issue by ConnorWalkers** [momo5502/boiii#600]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

Start the "boiii.exe".

### Expected Result

Game Starts

### Actual Result

The game locks in a black screen.

### (Optional) Proof and Additional Information

![tempsnip](https://user-images.githubusercontent.com/131823406/234412152-67547031-0f6a-4677-abb1-7dbf2c605337.png)
![Cattura](https://user-images.githubusercontent.com/131823406/234412185-2d204c3b-6c3b-4731-a28b-51878ef149e1.PNG)

### Severity/Priority

Medium

**Comment by pistakilla** [comment]
I'd ask this in the discord someone will be able to help. These issues can be solved ranging from broken game files, antivirus, or read/write permissions of a folder so asking here isn't really ideal.

**Comment by ConnorWalkers** [comment]
Oks, Thanks :3
