### ISSUE TITLE
When I launch the game, it closes after 5 seconds with no error message

### ISSUE THREAD

**Issue by MaskeZen945961** [momo5502/boiii#606]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

Hello, I have a problem with BOIII. When I launch the game, it closes after 5 seconds with no error message. I have already reinstalled the game 3 times and BOIII.exe 15 times, and I have uninstalled Avast and Ccleaner, but the problem remains. Does anyone have a solution ?

Console : https://cdn.discordapp.com/attachments/1073741856992669738/1100903493105090620/Call_of_Duty_Black_Ops_III_2023.04.26-23.53_clip_1.mp4

Game : https://cdn.discordapp.com/attachments/1073741856992669738/1100897206598385685/Call_of_Duty_Black_Ops_III_2023.04.26-23.30.mp4

### Expected Result

Fix it 

### Actual Result

Nothing happen and application crash

### Severity/Priority

High/Critical

**Comment by diamante0018** [comment]
Broken game files are attributed to this issue.

**Comment by MaskeZen945961** [comment]
I reinstalled window and it worked !
