### ISSUE TITLE
Mod menus aren’t showing up in boiii 

### ISSUE THREAD

**Issue by yunggxd09** [momo5502/boiii#612]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. All maps don’t work with mod menus
2. 
3. 

### Expected Result

i don’t know this question

### Actual Result

no errors it’s just mod menu aren’t showing up in solo zombies 

### (Optional) Proof and Additional Information

I downloaded a mod menu from steam workshop but after the new update it’s not working not even console commands when i play solo zombies 

### Severity/Priority

High/Critical

**Comment by pistakilla** [comment]
put `enable_zone_folder 1` in console.
