### ISSUE TITLE
Widows Wine removes Bowie Knife camo

### ISSUE THREAD

**Issue by BladedChild** [momo5502/boiii#613]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. Buy Bowie Knife
2. Buy Widows 
3. Bowie camo disapears

### Expected Result

Camo should stay

### Actual Result

Camo disappears 

### Severity/Priority

Minor

**Comment by FragsAreUs** [comment]
does this also happen on steam?

**Comment by BladedChild** [comment]
Not entirely sure. I can check that out in a couple of days when I'm able
to hop back on. I'll get back to you on that when I can

**Comment by MotoLegacy** [comment]
This does occur in the Steam and retail versions of Black Ops III. It even has an entry on the [Wiki](https://callofduty.fandom.com/wiki/Widow%27s_Wine):

*"If you buy Widow's Wine and you already have the Bowie Knife, it will lose it's equipped camo."*
