### ISSUE TITLE
Still dropping frames

### ISSUE THREAD

**Issue by ToxicMxstify** [momo5502/boiii#616]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1.  Launch boiii
2.  suffer fps drops
3. 

### Expected Result

After installing boiii i'd expect no more fps dropping on the game. but it is still happening

### Actual Result

still dropping frames heavily

### (Optional) Proof and Additional Information

![image](https://user-images.githubusercontent.com/132141662/235301952-f04e0f85-4cf9-4db9-9132-bdddef8d24e2.png)

frame drops by 70 in the menu's too

### Severity/Priority

High/Critical

**Comment by diamante0018** [comment]
There are many issues already opened for perf issues
