### ISSUE TITLE
Crash when im playing

### ISSUE THREAD

**Issue by Aceu97** [momo5502/boiii#618]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit)

### Reproducibility Rate

Medium: The bug can be reproduced intermittently

### Steps to Reproduce

1. I start the BO3 client
2. i start game zombie or multi
3. game crash after 3-4 minutes

### Expected Result

![bo3](https://user-images.githubusercontent.com/132170517/235325370-32406e51-d5b9-40b0-8038-2af71e44d861.PNG)

### Actual Result

When i play, my game crash, everytimes, after 5-6 minutes.
I installed 2 times the torrent T7_Fullgames, but same results.
I have a good pc, +200 fps on the game and good connection?
I dont know how to fix it.
Someone have solution for me ?

### (Optional) Proof and Additional Information

![crash](https://user-images.githubusercontent.com/132170517/235325057-2c7f15f5-c849-469f-acf0-286722a6c57c.PNG)
![craaaash](https://user-images.githubusercontent.com/132170517/235325064-a9dc43fd-6c54-4cda-a73a-383533de8b4a.PNG)
https://media.discordapp.net/attachments/782017951942967316/1101985033176231996/IMG_5528.jpg?width=507&height=676
https://media.discordapp.net/attachments/782017951942967316/1101985011424567406/IMG_5530.jpg?width=507&height=676
https://media.discordapp.net/attachments/782017951942967316/1101985012011765832/IMG_5529.jpg?width=507&height=676

### Severity/Priority

Medium

**Comment by diamante0018** [comment]
Wait for the game to finish downloading.

**Comment by Aceu97** [comment]
> Wait for the game to finish downloading.

i did, the first pics is useless idk why i put that but, i installed the game 100% 2 times but nothing :/
