### ISSUE TITLE
Option to use BO3 Weapons Instead of Custom Ones

### ISSUE THREAD

**Issue by jonathan570** [momo5502/boiii#619]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

An option to replace custom weapons with BO3 ones. This would be great for leveling up guns on maps you wouldn't be able to normally

**Comment by diamante0018** [comment]
I'm am 99% sure this is not possible without modifying the map itself.
The reason is that there would be errors as the client would have weapon indexes mismatch the value of the host (map hoster).
In short this would break the game 
If I'm wrong please correct me though.
