### ISSUE TITLE
Bad binary loaded into memory

### ISSUE THREAD

**Issue by xlizz** [momo5502/boiii#620]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. /
2. /
3. /

### Expected Result

well fixed idk

### Actual Result

/

### Severity/Priority

High/Critical

**Comment by diamante0018** [comment]
Not our issue.
