### ISSUE TITLE
When I close the client my saves resets

### ISSUE THREAD

**Issue by HAWAKEEN** [momo5502/boiii#627]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

when I close the client my saves resets completely 

### Expected Result

Maintain the client saves regularly

### Actual Result

It doesn't crush nothing of this just after quiting, when i re-open the client the progress are gone just like i installed for the first time the game

### Severity/Priority

High/Critical

**Comment by pistakilla** [comment]
Duplicate of #569

**Comment by HAWAKEEN** [comment]
> Duplicate of #569

And than?

**Comment by diamante0018** [comment]
Duplicate of #569
