### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by xlizz** [momo5502/boiii#629]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. i click on play
2. i get this message
3. 
4. 

### Expected Result

the game launches

### Actual Result

game crashes

### (Optional) Proof and Additional Information

[boiii-crash-2023-05-01-19-35-04.zip](https://github.com/momo5502/boiii/files/11366942/boiii-crash-2023-05-01-19-35-04.zip)

### Severity/Priority

High/Critical
![Capture](https://user-images.githubusercontent.com/132191240/235499773-ff1955eb-0d6c-4b82-9b1c-e4a66e8a11f0.PNG)

**Comment by diamante0018** [comment]
resolved

**Comment by xlizz** [comment]
> resolved

what does that mean diamente ?
