### ISSUE TITLE
Round of spiders spiders don't move

### ISSUE THREAD

**Issue by jonytest12** [momo5502/boiii#632]
### Bug Type

Dedicated Server

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Windows Server 2016

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1.map name:zero no shima
2.Round of spiders spiders don't move

### Expected Result

that they will move

### Actual Result

The app doesn't crash

### (Optional) Proof and Additional Information

https://streamable.com/exg4uq
![image](https://user-images.githubusercontent.com/88643357/235593666-9345d6e9-3fe6-4d46-bf0c-8520a139d738.png)

### Severity/Priority

Minor

**Comment by diamante0018** [comment]
Duplicate issue
