### ISSUE TITLE
The customs maps do not work

### ISSUE THREAD

**Issue by GUEPARDO2003YT** [momo5502/boiii#633]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. 
2. 
3. 

### Expected Result

The customs maps do not work

### Actual Result

The customs maps do not work

### Severity/Priority

High/Critical

**Comment by diamante0018** [comment]
That's not true as far as I'm aware.
Reach out for support in the testing Discord server.
