### ISSUE TITLE
When complete an Easter Egg on private game ,Friends who join don't have Gateworm 

### ISSUE THREAD

**Issue by WaltzSharp** [momo5502/boiii#639]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit), Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. Complete EE
2. 
3. 

### Expected Result

Complete EE 

### Actual Result

Only host completed it

### Severity/Priority

Medium

**Comment by DatenshiKuro** [comment]
It's also happened to me, pretty annoying :,(

**Comment by diamante0018** [comment]
There is really no point in is chasing hot join errors like this one. They even never be a priority for us.
I strongly suggest you and your friends all start playing at the same time.

**Comment by WaltzSharp** [comment]
Play at the same time is not possible 'cus there no possibility to joining before the game launch ,there no Friends list and there no joining command wich work to join lobby .We will like to play on priv serv but they are crashing pretty often
