### ISSUE TITLE
Fatal error after opening cutscene causes mini dump

### ISSUE THREAD

**Issue by CCLA1902** [momo5502/boiii#642]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. launch game 
2. opening cutscene plays 
3. error 

### Expected Result

i get an error after the cutscene ends that is a fatial error and it creates a minidump.

### Actual Result

error its the same one ive been having the past 2 days.

### (Optional) Proof and Additional Information

![](https://cdn.discordapp.com/attachments/1073741856992669738/1103410149625970688/image.png)
https://cdn.discordapp.com/attachments/1073741856992669738/1103410149844058244/boiii-crash-2023-05-03-14-57-04.zip

### Severity/Priority

High/Critical

**Comment by diamante0018** [comment]
Please come to the discord server so we can assist you in repairing the files

**Comment by CCLA1902** [comment]
> 

im in game chat 1
