### ISSUE TITLE
Error when loading client 

### ISSUE THREAD

**Issue by SPZIKE** [momo5502/boiii#644]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1.  I open the client 
2.  Error quit was not requested in the main thread 
3. 

### Expected Result

I should be able to play but i can load the client

### Actual Result

It displays an error 
![image](https://user-images.githubusercontent.com/131039721/236260968-6a6a443b-8c84-45be-84b1-c2b0751a4cd4.png)

### Severity/Priority

High/Critical

**Comment by momo5502** [comment]
#645
