### ISSUE TITLE
Client not launching 

### ISSUE THREAD

**Issue by MotionInOcean** [momo5502/boiii#645]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. 
2. 
3. 

### Expected Result

![boii](https://user-images.githubusercontent.com/132595586/236261285-ada16b03-49d5-4595-9563-bcea5dd004ab.png)

### Actual Result

game just isnt launching so cant play and multiple people have this

### (Optional) Proof and Additional Information

![boii](https://user-images.githubusercontent.com/132595586/236261535-94a60627-9925-47ae-9c93-c07884184f99.png)

### Severity/Priority

High/Critical

**Comment by chilllatley** [comment]
Same

**Comment by momo5502** [comment]
fixed. should be built in 10 mins
