### ISSUE TITLE
Implement CoD commands 

### ISSUE THREAD

**Issue by Adams2074** [momo5502/boiii#646]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

Implement/track useful cod commands like godmode, give***, noclip etc.  (i hope i wrote it how it should be )

**Comment by pistakilla** [comment]
This can be done simply by loading a mod and enabling `developer 2` in the console and putting `devmap mapname` and cheat commands are available.
