### ISSUE TITLE
Black screen when it starts then crash

### ISSUE THREAD

**Issue by C-Beile** [momo5502/boiii#652]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. 
2. 
3. 

When i start my game with the boiii client, the windows open but only with a black screen then it close itself again no error in the console just a black screen

### Expected Result

Nothing happend, it will crash again

### Actual Result

Nothing happend

### Severity/Priority

High/Critical

**Comment by diamante0018** [comment]
Hello, please seek help in the discord server.
You probably have broken game files.
