### ISSUE TITLE
I cant join the server and i paid for it

### ISSUE THREAD

**Issue by clyroxx** [momo5502/boiii#657]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

Low: The bug has only occurred once or a small number of times

### Steps to Reproduce

1. 
2. 
3. 

### Expected Result

i need the invite to the discord server

### Actual Result

i need the invite to the discord server

### (Optional) Proof and Additional Information

i need the invite to the discord server

### Severity/Priority

High/Critical

**Comment by diamante0018** [comment]
read the post on patreon

**Comment by clyroxx** [comment]
It won't let me enter the patreon, it says that I have to pay

**Comment by momo5502** [comment]
> It won't let me enter the patreon, it says that I have to pay

please post a screenshot of the error message. but you likely only have to read what it says
