### ISSUE TITLE
Running under Proton gets stuck on splash screen

### ISSUE THREAD

**Issue by InvoxiPlayGames** [momo5502/boiii#66]
With Black Ops 3, launched by Steam, running under Proton Experimental on SteamOS 3, and a Debug build of the latest commit of boiii, the game gets stuck on the splash screen. The stock game runs fine.

I've attached the Proton log file - I don't know how useful this is as there aren't many debug outputs from boiii itself (I'd added my own on DllMain to make sure the DLL was loading) and it all seems fairly standard, but maybe there's something useful to be found here.

[steam-311210.log](https://github.com/momo5502/boiii/files/9796600/steam-311210.log)

**Comment by momo5502** [comment]
Please create a process dump

**Comment by tpurde** [comment]
I'm willing to help with making Proton work when this client releases. Black Ops III on Steam works perfectly, so if you didn't use any super Windows-specific library, I think it should work fine? Nevertheless, I'll check this thread in the future for any testing requirements, and will be glad to help.

**Comment by momo5502** [comment]
I need a process dump when the game is stuck, otherwise there is nothing I can do

**Comment by tpurde** [comment]
> I need a process dump when the game is stuck, otherwise there is nothing I can do

How may I create this?

**Comment by momo5502** [comment]
I have no idea, you are the guys with a steam deck.

**Comment by tpurde** [comment]
Alright, I'll try the best I can. Although, I might need a compiled version. I think you've used Visual Studio for compilation, and that is not available here on Linux.

Extremely sorry for the disturbance, it's totally understandable if you don't want to waste time with Proton support until the client releases.

**Comment by momo5502** [comment]
This d7ba4ae856794c267a80ca091bda8a3f29a523c4 should fix the process wrapper to work under wine. This means proton support is exactly as far again as it was, when this issue was created :D

**Comment by tpurde** [comment]
I'll make sure to test this out when it's released! Thank you so much for the initial effort.

**Comment by momo5502** [comment]
Apparently this is fixed. Can anyone retest, to make sure?

**Comment by tpurde** [comment]
I don't think I can compile by myself, but if you can temporarily let me in the testing, I'll do it.

**Comment by tpurde** [comment]
Hey @momo5502, I don't have a Twitter. How about an e-mail?

**Comment by momo5502** [comment]
> Hey @momo5502, I don't have a Twitter. How about an e-mail?

sure: mauriceheumann@gmail.com

**Comment by tpurde** [comment]
Sent!

**Comment by tpurde** [comment]
I've got it working thanks to momo5502's advice to use the -launch parameter. 

Firstly, you need to add boiii.exe as a Non-Steam Game. Then, set the launch option to -launch as so: 
![image](https://user-images.githubusercontent.com/62025836/220650226-aff4f0ab-7726-441e-a58a-bcac342b8ac7.png)

And also, use Proton-GE or Proton-Experimental: 
![image](https://user-images.githubusercontent.com/62025836/220650309-e2e82bac-ca4a-4618-8181-3aaa98ffa960.png)

![Screenshot from 2023-02-22 16-51-43](https://user-images.githubusercontent.com/62025836/220650415-48513854-9ad4-407e-91f3-709998e0c19d.png)

**Comment by momo5502** [comment]
Will investigae why the launcher crashes, but I'm pretty sure this did the trick: https://github.com/momo5502/boiii/commit/cd8343e7f2ea24353107cc0d2a839ba3e3c15843
