### ISSUE TITLE
Which BO3 Version is needed to use the Client

### ISSUE THREAD

**Issue by MaxiAmZocken** [momo5502/boiii#661]
### Duplicate Issue Check

- [ ] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

There are multiple versions of bo3 on steam, is it important to get the "Zombies Chronicles Edition" or can I just buy the Multiplayer only version for 5 bucks less ? 

![image](https://user-images.githubusercontent.com/50016128/236848174-72434d40-eaee-4e5f-8182-2b77bac01a76.png)

**Comment by rec0veryyy** [comment]
To play multiplayer and zombies it is recommended to have the one worth 19€.

**Comment by Brentdevent** [comment]
Github issues are meant for feature requests and bug reports, these type of questions should be asked in the discord.

**Comment by rec0veryyy** [comment]
> Los problemas de Github están destinados a solicitudes de funciones e informes de errores, este tipo de preguntas deben hacerse en la discordia.

You're right, @MaxiAmZocken ask it in discord

**Comment by MaxiAmZocken** [comment]
which discord server, I thought there was only the one you get in if you pay, but because of this I don't know if I want to

**Comment by Brentdevent** [comment]
Any version is compatible with BOIII; however, it will only limit the content you receive with it. For example, the multiplayer starter pack does not include DLC maps for multiplayer, zombies, or the campaign. This is the decision you have to make.

The Discord is only accessible for sponsors, so is the client at the moment until its release.
