### ISSUE TITLE
Boiii won't launch

### ISSUE THREAD

**Issue by codyr48** [momo5502/boiii#664]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. I click on boiii.exe in my black ops 3 folder
2. a small boiii window pops up and I click play
3. a Black ops 3 window initially opens but is then replaced by the boiii console. 

### Expected Result

The game should start up.

### Actual Result

I am black screened for a short time before it just closes all together with no error message or anything.

### (Optional) Proof and Additional Information

not sure what I could upload as there's no error or crash messages being sent.

### Severity/Priority

Medium

**Comment by pistakilla** [comment]
Could be your antivirus. Ask in the discord for further support
