### ISSUE TITLE
Fatal error after clicking play on BOIII.exe

### ISSUE THREAD

**Issue by michaelmunday** [momo5502/boiii#665]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. Click play in client

![image](https://user-images.githubusercontent.com/113626388/236972023-b5f47da2-78a6-4f0c-a74b-941827feb72f.png)

### Expected Result

It will always crash

### Actual Result

Always get this error

### (Optional) Proof and Additional Information

I have the MP starter pack through Steam and dragged the BOIII.exe client right into the game files as soon as it finished installing. I've tried launching 15+ times and I only ever get this error. 
[boiii-crash-2023-05-08-18-35-26.zip](https://github.com/momo5502/boiii/files/11426378/boiii-crash-2023-05-08-18-35-26.zip)

### Severity/Priority

High/Critical

**Comment by diamante0018** [comment]
We will make some extra checks to make sure this crash is mitigated. 
The root cause however is something being seriously wrong on your end. Ether broken game files somehow or some mismatch between the boiii client files. Feel free to ask for further help from Discord.
