### ISSUE TITLE
Lua scripting support

### ISSUE THREAD

**Issue by rec0veryyy** [momo5502/boiii#668]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

Hi, good morning

Seeing that this project is progressing little by little I have been thinking about a feature that can be quite interesting, and it is the Lua Scripting support because H1 client supports both GSC and Lua, as you know it is a good scripting language and it is used by many projects for their clients such as FiveM, Multi Theft Auto (San andreas), Roblox, H1 COD client and many more, it would be interesting to take into account this feature because those who know Lua or have an interest in learning it will be happy, I am speaking from my ignorance and without knowing how this contruido the engine of COD BO3/BOiii and if it supports it, but if it is possible to do it would be great, greetings.

**Comment by diamante0018** [comment]
Hard no. Bad idea. GSC is perfectly fine

**Comment by rec0veryyy** [comment]
The problem with GSC is that it's complicated and poorly documented, if you can't do it, nothing happens, just wanted to let you know.

**Comment by diamante0018** [comment]
GSC has official documentation and the source code of the script is available. So your point is kind of invalid because adding LUA scripting would not solve your lack of documentation issue.

**Comment by diamante0018** [comment]
This is not a good investment of development time.
LUA support was added to the XLabs clients & clones because at the time there was no gsc compiler, but now there is one. LUA support lost all meaning even on Xlabs and one day it might even be removed!
