### ISSUE TITLE
Cg_FoVmin and other cvars

### ISSUE THREAD

**Issue by Dezmond19** [momo5502/boiii#671]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

I see that cg_fovmin and others are available through the console, but they don't seem to be functional. I have tried developer 2 and devmap to no avail. Is this possibly an engine limitation?

**Comment by diamante0018** [comment]
Please see #141 
Gonna use that issue to track al cg_fov related dvars.
