### ISSUE TITLE
Texture quality is horrible even though it is set to extra.

### ISSUE THREAD

**Issue by Kyle-rat** [momo5502/boiii#674]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. 
2. 
3. 

### Expected Result

My texture quality gets fixed

### Actual Result

The texture stays the same. 

### Severity/Priority

High/Critical

**Comment by diamante0018** [comment]
not a client issue
