### ISSUE TITLE
BOIII Fatal Error after getting to main menu screen 

### ISSUE THREAD

**Issue by fluidz420** [momo5502/boiii#677]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. launch boiii
2. wait or join server
3. crash within 10 mins, usually first two mins

### Expected Result

should be able to play normally 

### Actual Result

game crashes

### (Optional) Proof and Additional Information

/
[boiii-crash-2023-05-10-10-31-04.zip](https://github.com/momo5502/boiii/files/11443769/boiii-crash-2023-05-10-10-31-04.zip)
![My Great Capture Screenshot 2023-05-10 10-32-31](https://github.com/momo5502/boiii/assets/132933426/9ea49b91-728e-464e-95ef-70f423608f52)

### Severity/Priority

High/Critical

**Comment by diamante0018** [comment]
Your minidump reveals something is very wrong with your OS.
Possibly some windows security feature prevents boiii from loading the game properly from what I can tell.
Or broken game files too at this point. Please come to the boiii discord for further assistance.
