### ISSUE TITLE
Crashing when attempting to run a dedicated server with Linux

### ISSUE THREAD

**Issue by Stefanuk12** [momo5502/boiii#683]
### Bug Type

Dedicated Server

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Linux

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

*the files provided will link to the discord server, not the attachments themselves!*

1. Install [wine](https://wiki.winehq.org/Ubuntu)
2. Install `ntlm_auth` -> `sudo apt-get install ntlm_auth` (needed for something)
3. Download and execute the [install script](https://discord.com/channels/1073342477383245894/1073746888630735068/1106329470052335776)
4. Download and execute the [run script](https://discord.com/channels/1073342477383245894/1073746888630735068/1106330012187099230) within the installation

### Expected Result

For a dedicated server window to show up.

### Actual Result

An error shows saying "Invalid host application"

### (Optional) Proof and Additional Information

![image](https://github.com/momo5502/boiii/assets/42220813/7d198977-cb45-473a-891e-6fb05762034d)
[crash zip](https://github.com/momo5502/boiii/files/11467805/boiii-crash-2023-05-12-22-20-50.zip)

Wine outputs the following:
```
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0024:fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
0110:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 000000000354FE10
0024:fixme:secur32:get_cipher_algid unknown algorithm 23
0024:fixme:secur32:get_mac_algid unknown algorithm 200, cipher 23
0024:fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
0114:err:ole:com_get_class_object apartment not initialised
0024:fixme:dbghelp:MiniDumpWriteDump NIY MiniDumpWithHandleData
0024:fixme:dbghelp:MiniDumpWriteDump NIY MiniDumpScanMemory
0024:fixme:imm:ImeSetActiveContext (0000000000010052, 1): stub
0024:fixme:imm:ImmReleaseContext (0000000000010070, 0000000000010052): stub
00d0:fixme:imm:ImeSetActiveContext (0000000000010026, 0): stub
00d0:fixme:imm:ImmReleaseContext (0000000000010020, 0000000000010026): stub
```

Note that most of the output there is expected and normal. The main errors that need to be looked at probably are
```
0114:err:ole:com_get_class_object apartment not initialised
0024:fixme:dbghelp:MiniDumpWriteDump NIY MiniDumpWithHandleData
0024:fixme:dbghelp:MiniDumpWriteDump NIY MiniDumpScanMemory
```

### Severity/Priority

Medium

**Comment by diamante0018** [comment]
you need proton ge

**Comment by Stefanuk12** [comment]
I'll try that but note that using wine with the dedicated exe (not boiii) worked.

**Comment by diamante0018** [comment]
not really something we care about at the moment. we know proton get has black ops 3 patches.

**Comment by Stefanuk12** [comment]
i'll try with proton once i figure out how to but i have a feeling it's in part with boiii

**Comment by diamante0018** [comment]
doesn't really matter too be honest, you should host on windows.

**Comment by MattPeters13** [comment]
What discord is the install and run script stored in? I was going to try and check it out for you guys. I've done some Linux work in the past and might be able to contribute.

**Comment by Stefanuk12** [comment]
> What discord is the install and run script stored in? I was going to try and check it out for you guys. I've done some Linux work in the past and might be able to contribute.

BOIII testing. Reason I had it there is because it might include somethings that are supposed to be private

**Comment by Stefanuk12** [comment]
> doesn't really matter too be honest, you should host on windows.

the issue with hosting on windows is that the standard is linux. windows takes up too many resources and, mainly, doesn't support pterodactyl. majority of server architectures and solutions have moved to linux.

it's a shame this isn't a focus to fix, hopefully one day it will be

**Comment by Stefanuk12** [comment]
I believe the error originates from [here](https://github.com/momo5502/boiii/blob/bcc588d5e345d2e22591128b490ad059222e5302/src/client/launcher/html/html_frame.cpp#L267) based upon the message. I will test soon to verify.

**Comment by momo5502** [comment]
> I believe the error originates from [here](https://github.com/momo5502/boiii/blob/bcc588d5e345d2e22591128b490ad059222e5302/src/client/launcher/html/html_frame.cpp#L267) based upon the message. I will test soon to verify.
> 
> Edit: this is not the case. After logging the exceptioninfo's code and address, I got the following: `3221225477 --- 00000001400FF5CC`
> 
> There's some undefined behaviour happening somewhere and likely is an array out-of-bounds access. I will try to investigate further...
> 
> I tried to get a stack traceback but the debug symbols weren't converting. If you know how to, please let me know. Anyway, the stack traceback goes back 25 levels if that's helpful
> 
> Edit: I have found the line that errors -> https://github.com/momo5502/boiii/blob/main/src/common/utils/com.cpp#L127 . The function on that line returns HResult of `-2147221008` or `800401F0` . [Here's](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/f8417fdc-03e3-4f73-b165-b39a90fb1b90/cocreateinstance-fails-with-return-code-2147221008) a post explaining the error possibly? The error code is `CO_E_NOTINITIALIZED`
> 
> Edit: I fixed the error by calling `CoInitialize(nullptr);` before `CoCreateInstance`. However, this did not fix the actual error sadly.
> 
> Edit: After commenting the line that adds `generate_crash_info` to the zip minidump, I was able to get a crash zip. [boiii-crash-2023-05-12-22-20-50.zip](https://github.com/momo5502/boiii/files/11467805/boiii-crash-2023-05-12-22-20-50.zip)

The entire COM infrastructure is disabled when running BOIII properly with proton. You are debugging non-issues right now as you are not correctly setting things up with proton ge.

**Comment by Stefanuk12** [comment]
Yeah I realised that, unfortunately I have no clue how to get proton ge working.

**Comment by diamante0018** [comment]
Momo is working on making the client work inside a docker container (using at least wine).
I strongly advise following the progress of #712
