### ISSUE TITLE
Playtime saving to steam?

### ISSUE THREAD

**Issue by drewtkay** [momo5502/boiii#686]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

Hey, noticed that the playtime displays correctly for the session but once closed doesn't save to BlackOps3's playtime

Not a major suggestion by any means, may not be possible due to the emulated server - not to sure at all in all honestly

But if possible, maybe be a good idea!

Super low priority of course

Thanks!

**Comment by diamante0018** [comment]
Not planned
