### ISSUE TITLE
Add bots to public lobbies?

### ISSUE THREAD

**Issue by NotAdamGamingLOL** [momo5502/boiii#69]
I managed to load into a match by myself, then tried spawning bots to level up with, but I can't figure it out. I know I could just play custom games, but I want to progress through the levels while I play. I also couldn't find the commands to turn custom games into public matches.

**Comment by pistakilla** [comment]
You can just inject a gsc script using this https://github.com/shiversoftdev/t7-compiler.

Then just code a script to spawn bots when you spawn.

**Comment by joseupp** [comment]
> 
How did you get a public game to start?
,by editing the playlist you can make the bots play.

**Comment by LevelChecker** [comment]
> > 
> 
> How did you get a public game to start? ,by editing the playlist you can make the bots play.

How can you make the bots play? its not hard to make the match start

**Comment by joseupp** [comment]
> 

Can you tell me how to start a public game?.
in any other previous game the playlist is edited and the commands are added so that the bots connect, I want to try commands in this one but I am unable to search and start a public game, it stays looking for a game.

**Comment by LevelChecker** [comment]
> > 
> 
> Can you tell me how to start a public game?. in any other previous game the playlist is edited and the commands are added so that the bots connect, I want to try commands in this one but I am unable to search and start a public game, it stays looking for a game.

Just share with me how you can start bots when you figure it out bro, thank you

do this when it is searching for a game
\launchGame;party_minplayers 1

**Comment by CrazyCSIW6** [comment]
You were previously able to inject GSC scripts, but since BOIII now uses its own executable rather than a DLL on top of the original executable, it's no longer possible with tools made for unmodified T7.

**Comment by momo5502** [comment]
There is now a `spawnBot` command you can use
