### ISSUE TITLE
Console 4 Player Local Multiplayer in BOIII?

### ISSUE THREAD

**Issue by greppim** [momo5502/boiii#692]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

Could this feature be restored? Or has it been stripped completely out of the game? Currently it only supports upto 2, whereas consoles upto 4.

**Comment by diamante0018** [comment]
I don't even know what you are describing for sure. Are you talking about split screen?
Anyway, it's stripped out if I understood your question.

**Comment by greppim** [comment]
Yeah, split-screen.

I see, didn't know if there were any leftovers in the engine.

**Comment by diamante0018** [comment]
It's not worth our development time I think. Too hard of a feature to implement.
You can play with your friends on a dedi server.

**Comment by greppim** [comment]
Sure, I understand. Thanks for the reply though.
