### ISSUE TITLE
Controller Detection Broken Alt Tab

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [momo5502/boiii#693]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. Open the BOIII client with a controller connected (I use a PS4 one)
2. Alt Tab out of the game at any point
3. Alt Tab back into the game, whilst the base game would detect what you're using and switch on the fly, the BOIII client gets switched back to mouse and keyboard and does not switch back

### Expected Result

The game should detect what you're using and switch based on the last input

### Actual Result

The game gets stuck in mouse and keyboard mode and will not switch back to controller input

### Severity/Priority

High/Critical

**Comment by momo5502** [comment]
not reproducible on my end. works perfectly fine with my ps4 controller. this needs more info

**Comment by KUPOinyourWINDOW** [comment]
strange, on my end it happens every time, I have the game added to steam as a non steam game and I don't use any external programs, what kind of info would be helpful?

**Comment by pistakilla** [comment]
> Strange, on my end it happens every time, I have the game added to steam as a non steam game and I don't use any external programs, I'm using my PS4 controller via wired USB. What kind of info would be helpful?

Bo3 already supports dualshock 4, just plug and play. Don't rely on steam to fix your issue, matter in fact, don't use steam controller support because it's total garbage.

**Comment by KUPOinyourWINDOW** [comment]
> > Strange, on my end it happens every time, I have the game added to steam as a non steam game and I don't use any external programs, I'm using my PS4 controller via wired USB. What kind of info would be helpful?
> 
> Bo3 already supports dualshock 4, just plug and play. Don't rely on steam to fix your issue, matter in fact, don't use steam controller support because it's total garbage.

Whilst I respect your opinion telling me just to not use it doesn't fix this issue (and makes my controller stop working with base black ops 3 in the first place). 

For some reason though the BOIII client won't register my controller after alt tabbing out and then back into the game, even with it not added to steam (I just tested), and its reproducable on my end every time without fail. I'm at a loss so any advice on info that might be useful would be appreciated!

**Comment by diamante0018** [comment]
Try with steam closed.

**Comment by KUPOinyourWINDOW** [comment]
No change with steam closed, but after installing DS4Windows and the drivers that program installs its now working as intended, even if I alt tab.
