### ISSUE TITLE
Game wont launch

### ISSUE THREAD

**Issue by Samex5** [momo5502/boiii#701]
Bug Type
Client

BOIII Version
v0.0.1 (Latest)

Environment (Operating System)
Microsoft Windows 10 Pro (64-Bit)

Reproducibility Rate
High: The bug can (almost) always be reproduced

Steps to Reproduce
This bug doesn't take steps. I simply launch the client and i get the

Expected Result
Game should launch

Actual Result
When i start the boiii client and try to run the game it starts but i only get a black screen for 2-3 seconds and than it instantly crashes.

Additional Information
I verified my bo3 files trough steam and it all checks up i tried redownloading boiii client but nothing changes my issue.

Severity/Priority
Minor

**Comment by diamante0018** [comment]
It's most likely it is windows memory integrity doing this. In the future ask this question in the discord there is nothing you can do here to fix your game that you can't do in the Discord.

**Comment by diamante0018** [comment]
Either send minidumps here or on the discord

**Comment by Samex5** [comment]
> Either send minidumps here or on the discord

Where do i get the mini dumps?

**Comment by diamante0018** [comment]
That's something to ask in the discord server. I don't have time to help you here

**Comment by diamante0018** [comment]
Closing this unless it is proven via minidump issue is related to the client
