### ISSUE TITLE
Connecting to custom games match breaks

### ISSUE THREAD

**Issue by AEAEAEAE4343** [momo5502/boiii#71]
When I connect to a custom games match from another client (tried the same pc, and another over network), the game stops working and I get a connection interrupted message. The second client tries to connect but fails in the end.

While connecting:
![image](https://user-images.githubusercontent.com/34800109/198853794-3ed3b158-8833-4d3a-9ce1-f58b0c200ae0.png)

Result:
![image](https://user-images.githubusercontent.com/34800109/198853857-fc1be0d1-f664-487c-a07f-f15dd9ee8490.png)

**Comment by LevelChecker** [comment]
probably because it's still being worked on atm

**Comment by momo5502** [comment]
This is on purpose. I left essential parts uncommitted.

**Comment by AEAEAEAE4343** [comment]
Okay! Just curious though: why would you leave out parts for multiplayer support? Isn't that a core thing a client should have?

**Comment by momo5502** [comment]
Because it's unfinished and has a few issues. I left the part out so that people would notice it doesn't work yet and just patiently wait until the feature is ready instead of wasting my time and complaining that it doesn't work. However, that obviously didn't help.
