### ISSUE TITLE
SND mode what dvars needed as game does not stop once all players die.

### ISSUE THREAD

**Issue by OhMadTec** [momo5502/boiii#716]
### Bug Type

Dedicated Server

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. set up as snd problem occurs
2. 
3. 

### Expected Result

round ends once all players die

### Actual Result

game continues until countdown is over

### (Optional) Proof and Additional Information

currently live trying to make/fix this. 

### Severity/Priority

???

**Comment by diamante0018** [comment]
wait for dss0's config to be updated. not a client issue.
