### ISSUE TITLE
feature request: make cl_yawspeed modifiable

### ISSUE THREAD

**Issue by NotDqrk** [momo5502/boiii#719]
please allow this dvar to be used, it is so helpful and i cant play the servers i want to without it. Thanks.

0x8375EB80 - Type: FLOAT1 - cl_yawspeed

**Comment by diamante0018** [comment]
trick shotter moment

**Comment by NotDqrk** [comment]
its useable on all modded clients, is there a reason its not on boiii?

**Comment by mjkzy** [comment]
there's a chance the dvar just wasn't modifiable/added in bo3, nothing more nothing less
