### ISSUE TITLE
LAN

### ISSUE THREAD

**Issue by FLEXnFLEX** [momo5502/boiii#72]
are we able to play lan private match without steam by this project?

**Comment by LevelChecker** [comment]
No not right now nothing lan or online is functioning, this is in very early development

**Comment by momo5502** [comment]
It theoretically works, but there are a few bugs, so the functionality is disabled right now

**Comment by nkoxsw1331** [comment]
I'd love to hear an update on this matter. This is the biggest barrier for contribution for many.

**Comment by momo5502** [comment]
This works

**Comment by MisterCatOfficial** [comment]
How to play a lan game?
Seriously. i dont know how it works.

**Comment by Thatguy553** [comment]
> How to play a lan game? Seriously. i dont know how it works.

Me and a buddy were able to play "lan" via Hamachi.
Basically got on the same hamachi network,
launched through BOIII, and host needs to start the game and get past the cutscene, 
then those who want to join need to open the debug console and use /connect command with the hosts hamachi ipv4 and port 
/connect ipv4:27017 is what we usually do.

**Comment by FLEXnFLEX** [comment]
> > How to play a lan game? Seriously. i dont know how it works.
> 
> Me and a buddy were able to play "lan" via Hamachi. Basically got on the same hamachi network, launched through BOIII, and host needs to start the game and get past the cutscene, then those who want to join need to open the debug console and use /connect command with the hosts hamachi ipv4 and port /connect ipv4:27017 is what we usually do.

Well done, can we play the custom made maps??

**Comment by Thatguy553** [comment]
> > > How to play a lan game? Seriously. i dont know how it works.
> > 
> > 
> > Me and a buddy were able to play "lan" via Hamachi. Basically got on the same hamachi network, launched through BOIII, and host needs to start the game and get past the cutscene, then those who want to join need to open the debug console and use /connect command with the hosts hamachi ipv4 and port /connect ipv4:27017 is what we usually do.
> 
> Well done, can we play the custom made maps??

I would imagine so, but I havent tried custom maps with the friend yet. Mods however work fine. Though we do have a minor issue on Origins where only the host can see icons popup for things like generators being attacked, or the timer icon doesnt countdown for anyone other than the host when a player is down.
