### ISSUE TITLE
Server script error when starting solo custom map 

### ISSUE THREAD

**Issue by Stormiswe1** [momo5502/boiii#727]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. Download any custom map
2. Start the map in solo 
3. You get kicked instalty after the map loading screen appear

### Expected Result

The map should start without any problem 

### Actual Result

When i start the map i get this error (in solo) 
![image](https://github.com/momo5502/boiii/assets/127261334/f1594c2b-32fd-4444-8c43-815532bbc6da)

I tried with the steam version and everything is fine

I tried to play the map with some people (they were able to start their map without any problem) by joing directly through radmin, the map does load but i get awful fps (around 30 instead of over 120)

I have the same error for all custom maps

### (Optional) Proof and Additional Information

[Custom_map_error.txt](https://github.com/momo5502/boiii/files/11499262/Custom_map_error.txt) this is the entire console from loading the map the the error

[custom_map_error2.txt](https://github.com/momo5502/boiii/files/11499309/custom_map_error2.txt) This is the console with the error

### Severity/Priority

High/Critical

**Comment by Stormiswe1** [comment]
I did turned off developer settings

**Comment by Brentdevent** [comment]
`Starting up server with developer TRUE`

**Comment by Stormiswe1** [comment]
hum i guess it mean that i have developper enable, but its not.... 
![image](https://github.com/momo5502/boiii/assets/127261334/3c8e5726-b3b7-421d-9501-5008a5beedde)

**Comment by Stormiswe1** [comment]
Well I don't know what to say my windows is clean, everything is working, other default bo3 map  apart for custom maps

**Comment by Brentdevent** [comment]
Try deleting `boiii_players\user\config.cfg` and open the game.

**Comment by Stormiswe1** [comment]
Alr it worked quit a strange behaviour
![image](https://github.com/momo5502/boiii/assets/127261334/2950f945-3d9a-4583-af6a-11e193447abd)

Anyway thanks a lot, have a nice day
