### ISSUE TITLE
So I finally purchase bo3 on steam 

### ISSUE THREAD

**Issue by yunggxd09** [momo5502/boiii#730]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. 
2. 
3. 

### Expected Result

When I launch bo3 steam online services works perfectly fine but I launch boiii client it gives me an error code aft 

### Actual Result

I keep deleting “players” folder and resetting my networks nothing works 

### Severity/Priority

High/Critical

**Comment by diamante0018** [comment]
Support queries as such belong to the Discord server. Thanks.
You provide no useful info by the way so helping you here is already not possible.
