### ISSUE TITLE
Cannot connect to 97% of the servers.

### ISSUE THREAD

**Issue by fxyqq** [momo5502/boiii#735]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. 
2. 
3. 

### Expected Result

Be able to join the server.

### Actual Result

I get kicked for "lost connection to host"

![image](https://github.com/momo5502/boiii/assets/75327915/b21e30c9-a688-4732-9ffa-2c92fb875d69)

### (Optional) Proof and Additional Information

When you connect to a server this happens mostly on multiplayer it gets stuck on the loading screen into the game and in the console it prints some stuff

```
Error: Could not find fx "dlc2/island/fx_thrash_rage_gas_leg_rgt".
Error: Could not find fx "dlc2/island/fx_thrash_rage_gas_torso".
Error: Could not find fx "electric/fx_elec_warlord_damage_1".
Error: Could not find fx "electric/fx_elec_warlord_damage_2".
Error: Could not find fx "electric/fx_elec_warlord_lower_damage_1".
Error: Could not find fx "electric/fx_elec_warlord_lower_damage_2".
Error: Could not find fx "explosions/fx_exp_warlord_death".
Error: Could not find fx "fire/fx_fire_ai_human_arm_left_loop_optim".
Error: Could not find fx "fire/fx_fire_ai_human_arm_right_loop_optim".
Error: Could not find fx "fire/fx_fire_ai_human_head_loop_optim".
Error: Could not find fx "fire/fx_fire_ai_human_hip_left_loop_optim".
Error: Could not find fx "fire/fx_fire_ai_human_hip_right_loop_optim".
Error: Could not find fx "fire/fx_fire_ai_human_leg_left_loop_optim".
Error: Could not find fx "fire/fx_fire_ai_human_leg_right_loop_optim".
Error: Could not find fx "fire/fx_fire_ai_human_torso_loop_optim".
Error: Could not find fx "light/fx_light_body_glow_warlord".
Error: Could not find fx "light/fx_light_eye_glow_warlord".
Error: Could not find fx "player/fx_plyr_ability_screen_blur_overdrive".
Error: Could not find fx "vehicle/fx_exhaust_jetpack_warlord_juke".
Client: Registering configstring index 3241 with data y€‚tC
```

![image](https://github.com/momo5502/boiii/assets/75327915/8d8a0c3e-ec78-4b42-b0ba-4f288c11f75d)

![image](https://github.com/momo5502/boiii/assets/75327915/b21e30c9-a688-4732-9ffa-2c92fb875d69)

### Severity/Priority

High/Critical

**Comment by fxyqq** [comment]
I have also contacted the server authors and they say it's a common issue and it's the client's bug.

**Comment by diamante0018** [comment]
This is not the case for any other regular boiii user.
Seek help on the discors server. You might need to ensure your game is repaired and then we will determine who's issue this is.

**Comment by fxyqq** [comment]
i have asked most of the server authors this is a common issue
