### ISSUE TITLE
Make autobalance ignore bots

### ISSUE THREAD

**Issue by FrancescoCode1** [momo5502/boiii#740]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

**The Problem:**
Currently autobalance works by evenly distributing players between the two teams. While it works as intended, it doesn't differenciate between human players and bots. This often causes a team of 8 humans to play against a team of 7 bots and 1 human player. 
One of the issues is, that the human team scores much faster killstreaks which in turn leads to frustration in the enemy team. 

**Suggestion:** 
Autobalancing only based on human player distribution in the teams. This way there will always be a balance regardless of how many bots are in each team.

**Comment by diamante0018** [comment]
It's sounds almost as if you are asking us to run your dedi for you. Auto balancing does just that. It balances the teams.
I can give you a few suggestions like running a bot manager like this one to ensure that when real players join bots are equally kicked. https://github.com/DoktorSAS/GSC/blob/main/S1/autobots.gsc
Also you can run a server without bots.
How you decide to balance your server should kinda be your responsibility
