### ISSUE TITLE
BOIII ERROR CODE A....F...T 

### ISSUE THREAD

**Issue by yunggxd09** [momo5502/boiii#749]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. 
2. 
3. 

### Expected Result

i dont know how to answer that but i know made other compliants about this issue but here are some screenshots i can connnect to online when i launch bo3 on steam but when i launch the boiii client and when i click on "play online' it says emulating online service when it done it gives me an error code a...f...t i know explain this before but i want to share screenshots though

### Actual Result

i literally tired eveything nothing works 

### (Optional) Proof and Additional Information

![Steam 5_18_2023 8_45_26 AM](https://github.com/momo5502/boiii/assets/129239354/79244faa-0fb1-4f8d-8c28-4d1a6461211a)
![Call of Duty®  - ship - morenoedwardmake 5_18_2023 8_58_05 AM](https://github.com/momo5502/boiii/assets/129239354/b070d811-94f9-4a2f-bda2-e73ddebc7cd0) -without the boiii client i can play online 

![BOIII - yungkiller 5_18_2023 8_42_17 AM](https://github.com/momo5502/boiii/assets/129239354/096969d7-a9bf-42bb-8d5e-ccae29272162) -with the boiii client i can't play online 

### Severity/Priority

High/Critical

**Comment by diamante0018** [comment]
Duplicate issue. Unfortunately I do not have the time to go find it but you should have before opening this one. 😄
