### ISSUE TITLE
Game crashes on startup after finishing first download

### ISSUE THREAD

**Issue by Duckman123123** [momo5502/boiii#756]
Whenever i reinstall the mod menu i follow each of the steps perfectly but the game will continue to crash on start up no matter what I end up doing

**Comment by diamante0018** [comment]
Duplicate issue. Might be many things including antivirus

**Comment by CinderaceNamedEmber** [comment]
Go into your anti-virus software settings and whitelist/exclude the Black Ops III game folder & whitelist the boiii.exe file as well to prevent your anti-virus breaking it.

If you need further help, hop into the Discord's **#help-client** channel
