### ISSUE TITLE
Not Detecting Mods/Custom Maps

### ISSUE THREAD

**Issue by HackersinSpace** [momo5502/boiii#78]
So the latest update for the new BOIII.exe v0.0.1.285 has a major issue for me when I double click the BOIII.exe application, I go to Mods and there are no mods present as well as my custom maps downloaded. I do have them downloaded from the Steam Workshop and they do show up in the regular unmodded BO3.exe app.

**Comment by momo5502** [comment]
Fixed with 43a97addee8c95e268b87400beca28c5e940ada7.
Steam UGC interface vtable id has changed
