### ISSUE TITLE
Crashes on boot

### ISSUE THREAD

**Issue by joseupp** [momo5502/boiii#80]
Since the change to executable file I can't start the game, it closes at startup. 

Does it happen to anyone else? 

any solution?

**Comment by momo5502** [comment]
did you delete the leftover d3d11.dll?

**Comment by joseupp** [comment]
> did you delete the leftover d3d11.dll?

Yes, I have even downloaded a clean copy from steam and the same thing happens.

**Comment by momo5502** [comment]
then describe the issue, what kind of crash, does it create a minidump? does it throw an error?

**Comment by joseupp** [comment]
> then describe the issue, what kind of crash, does it create a minidump? does it throw an error?
look what happens,
https://youtu.be/H0fhgcqFfyY

**Comment by momo5502** [comment]
The video is very weird. Let me summarize to see if i get it: You launch the game. The scaling is pretty werid, but i assume that's not the issue. Console starts, main window pops up, game suddenly stops.

**Comment by momo5502** [comment]
That feels like the game's cheat detection triggering. The game does that when it detects cheat tools. I patched that for a few tools I use, but didn't care about other tools. E.g. cheat engine, x64dbg, windbg or other tools one might consider cheat tools or debuggers or disassemblers might still trigger it.
I recommend closing all of them. Maybe even rebooting your pc

**Comment by joseupp** [comment]
> That feels like the game's cheat detection triggering. The game does that when it detects cheat tools. I patched that for a few tools I use, but didn't care about other tools. E.g. cheat engine, x64dbg, windbg or other tools one might consider cheat tools or debuggers or disassemblers might still trigger it. I recommend closing all of them. Maybe even rebooting your pc

I don't have any cheat program or anything like that, the .dll version and the original steam version work perfectly, but neither .exe version has worked for me.
As I have told you, I have downloaded a clean version from Steam, I have tried different languages, I have removed dlc... nothing works.
This has happened to me with all .exe versions.

**Comment by diamante0018** [comment]
Can it even create a dump if this is empty?

https://github.com/momo5502/boiii/blob/main/src/client/component/exception.cpp#L192

**Comment by momo5502** [comment]
> > That feels like the game's cheat detection triggering. The game does that when it detects cheat tools. I patched that for a few tools I use, but didn't care about other tools. E.g. cheat engine, x64dbg, windbg or other tools one might consider cheat tools or debuggers or disassemblers might still trigger it. I recommend closing all of them. Maybe even rebooting your pc
> 
> I don't have any cheat program or anything like that, the .dll version and the original steam version work perfectly, but neither .exe version has worked for me. As I have told you, I have downloaded a clean version from Steam, I have tried different languages, I have removed dlc... nothing works. This has happened to me with all .exe versions. watch the video where I try all the versions https://youtu.be/fzVly1bY-Fg

have you tried removing the dxgi.dll? should be reshade, right? also what does the windows event log say?

**Comment by joseupp** [comment]
> > > That feels like the game's cheat detection triggering. The game does that when it detects cheat tools. I patched that for a few tools I use, but didn't care about other tools. E.g. cheat engine, x64dbg, windbg or other tools one might consider cheat tools or debuggers or disassemblers might still trigger it. I recommend closing all of them. Maybe even rebooting your pc
> > 
> > 
> > I don't have any cheat program or anything like that, the .dll version and the original steam version work perfectly, but neither .exe version has worked for me. As I have told you, I have downloaded a clean version from Steam, I have tried different languages, I have removed dlc... nothing works. This has happened to me with all .exe versions. watch the video where I try all the versions https://youtu.be/fzVly1bY-Fg
> 
> have you tried removing the dxgi.dll? should be reshade, right? also what does the windows event log say?

Yes, it is reshade, I have also tried without the same result, I am attaching the windows event viewer screen.

![Captura de pantalla 2022-11-21 200728](https://user-images.githubusercontent.com/108338623/203138954-3237cd8a-55fa-425b-88bc-efa180fe8154.png)

**Comment by momo5502** [comment]
i have a feeling i know what causes this. can you please try to enable procdump as post mortem debugger, as described here: https://knowledgebase.paloaltonetworks.com/KCSArticleDetail?id=kA14u000000CpfyCAC&lang=en_US%E2%80%A9
this should create a dump as soon as a process crashes. if that happens, pls attach the dump of boiii. i recommend to compress it as zip file, as they can get pretty big.

**Comment by joseupp** [comment]
> Tengo la sensación de que sé qué causa esto. ¿Puede intentar habilitar Procdump como depurador post mortem, como se describe aquí:https://knowledgebase.paloaltonetworks.com/KCSArticleDetail?id=kA14u000000CpfyCAC&lang=en_US%E2%80%A9Esto debería crear un volcado tan pronto como se bloquee un proceso? Si eso sucede, pls adjuntar el volcado de BOIII. Recomiendo comprimirlo como archivo zip, ya que pueden llegar a ser bastante grandes.

has generated these 2 dumps

https://drive.google.com/file/d/1eOl3CFz59nwqVuCegubzYJwxJuQ6lLJo/view?usp=share_link
https://drive.google.com/file/d/1kiDPEf0KexOg-MCQfmgN5h0OmGkUkY7w/view?usp=share_link

**Comment by joseupp** [comment]
hello momo any news regarding this error?

**Comment by momo5502** [comment]
no
