### ISSUE TITLE
Rename BO3 bots like H1-mods and plutonium

### ISSUE THREAD

**Issue by amrurikaj** [momo5502/boiii#91]
Suggestion to allow change bots name from [3arc] bots name to name we preferred.

**Comment by momo5502** [comment]
This has already been done.

**Comment by momo5502** [comment]
https://github.com/momo5502/boiii/commit/daedb0fcc6451fbce32ee44cdd83a97264f52fe1

**Comment by amrurikaj** [comment]
thanks 😎👍

**Comment by momo5502** [comment]
Reading botnames from file might be desirable

**Comment by Azzurys** [comment]
working on it tonight
