### ISSUE TITLE
 Several things

### ISSUE THREAD

**Issue by joseupp** [momo5502/boiii#96]
First of all, thank you very much for this gift that you are giving us called BOIII.
I am going to put several things that I have seen over the 3 prestiges since you have put the bots in public games.
In public matches with bots:
   -bots only know how to play tdm, in objective games they pass by.
   -bots always use the same specialist (ruin), (This is secondary and for informational purposes).
Is it possible to create a command for the bots to autoconnect to public games?
Is it possible for public matches to start automatically? currently they only start when you run the \launchgame command.
Other things for informational purposes and of less importance.
   -Currently it is not possible to change the calling card or emblem.
Thanks momo.

**Comment by momo5502** [comment]
Marked this as a feature. Will probably need to be split up into different issues.

**Comment by joseupp** [comment]
> Marked this as a feature. Will probably need to be split up into different issues.

Momo just needs to start the game automatically and the change of calling cards.

The rest of the problems are solved with gsc

- [x] bots only know how to play tdm, in objective games they pass by. --- GSC
- [x] bots always use the same specialist (ruin). --- GSC
- [x] Is it possible to create a command for the bots to autoconnect to public games? --- GSC
- [ ] Is it possible for public matches to start automatically? 
- [ ] Currently it is not possible to change the calling card or emblem.

Thanks momo.
